In [35]:
import polars as pl
pl.Config.set_tbl_cols(300).set_fmt_str_lengths(400).set_tbl_rows(20)

polars.config.Config

In [8]:
code_houseing = ["45211200", "45211000", "45211100", "45211300", "45211340"]

raw = pl.read_csv(
    "../data/raw_data/Contractació_pública_a_Catalunya__publicacions_a_la_Plataforma_de_serveis_de_contractació_pública_20260317.csv"
    ).filter(
        pl.col("codi_cpv").str.starts_with(code_houseing[0]) |
        pl.col("codi_cpv").str.starts_with(code_houseing[1]) |
        pl.col("codi_cpv").str.starts_with(code_houseing[2]) |
        pl.col("codi_cpv").str.starts_with(code_houseing[3]) |
        pl.col("codi_cpv").str.starts_with(code_houseing[4]) 
    ).filter(
        pl.col("resultat").is_not_null()
    ).select(
        pl.col("codi_expedient").alias("id"),
        pl.col("objecte_contracte").alias("title"),
        pl.col("enllac_publicacio").alias("link_href"),
        pl.col("resultat").alias("status"),
        pl.col("termini_presentacio_ofertes").str.extract(r"\d{4}", 0).cast(pl.Int32).alias("year"),
        pl.col("valor_estimat_contracte").fill_null(0).alias("estimatedAmount"),
        pl.col("import_adjudicacio_sense_iva").alias("payableAmount"),
        pl.col("lloc_execucio").alias("city"),
        pl.col("durada_contracte").alias("duration"),
        pl.col("identificacio_adjudicatari").alias("cif_provider"),
        pl.col("denominacio_adjudicatari").alias("name_provider")
    )
len(raw)
duplicated = raw.unique()
len(duplicated)

303

In [3]:
raw

shape: (303, 11)
┌─────────┬─────────┬────────┬────────┬──────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ id      ┆ title   ┆ link_h ┆ status ┆ year ┆ estima ┆ payabl ┆ city   ┆ durati ┆ cif_pr ┆ name_p │
│ ---     ┆ ---     ┆ ref    ┆ ---    ┆ ---  ┆ tedAmo ┆ eAmoun ┆ ---    ┆ on     ┆ ovider ┆ rovide │
│ str     ┆ str     ┆ ---    ┆ str    ┆ i32  ┆ unt    ┆ t      ┆ str    ┆ ---    ┆ ---    ┆ r      │
│         ┆         ┆ str    ┆        ┆      ┆ ---    ┆ ---    ┆        ┆ str    ┆ str    ┆ ---    │
│         ┆         ┆        ┆        ┆      ┆ f64    ┆ str    ┆        ┆        ┆        ┆ str    │
╞═════════╪═════════╪════════╪════════╪══════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ 2020041 ┆ L'objec ┆ https: ┆ Formal ┆ 2022 ┆ 4.9876 ┆ 500.00 ┆ Girona ┆ 75     ┆ B62890 ┆ VISORE │
│ 499     ┆ te del  ┆ //cont ┆ itzaci ┆      ┆ e6     ┆        ┆        ┆ anys 0 ┆ 751    ┆ N SL   │
│         ┆ present ┆ ractac ┆ ó      ┆      ┆        ┆        ┆        ┆ mesos  ┆        ┆        │
│         ┆ contrac ┆ iopubl ┆        ┆      ┆        ┆        ┆        ┆ 0 dies ┆        ┆        │
│         ┆ te és   ┆ ica.ca ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ la tran ┆ t/ca/d ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ smissió ┆ etall- ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ onerosa ┆ public ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ i const ┆ acio/c ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ itució  ┆ eb149b ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ d'un    ┆ 8-1845 ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ dret de ┆ -3f0c- ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ superfí ┆ 8279-1 ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ cie per ┆ c8939e ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ un      ┆ a0c3c/ ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ termini ┆ 200024 ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ de 75   ┆ 086    ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ anys    ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ sobre   ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ una     ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ finca   ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ de prop ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ ietat   ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ de l'Aj ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ untamen ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ t de    ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Girona  ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ integra ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ da dins ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ el Patr ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ imoni   ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ municip ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ al de   ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Sòl i   ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Habitat ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ ge      ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ situada ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ al      ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ carrer  ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Agudes  ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 72-74   ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ de      ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Girona, ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ amb ref ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ erència ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ cadastr ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ al 3667 ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 401DG84 ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 36H0001 ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ OM als  ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ efectes ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ de proc ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ edir a  ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ la prom ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ oció,   ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ constru ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ cció i  ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ gestió  ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ d'habit ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ atges   ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ de pr…  ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│ 23/013  ┆ Obres   ┆ https: ┆ Formal ┆ 2023 ┆ 1.4563 ┆ 108364 ┆ Barcel ┆ 2 anys ┆ A48010 ┆ OBRASC │
│         ┆ de cons ┆ //cont ┆ itzaci ┆      ┆ e7     ┆ 83.37  ┆ ona    ┆ 8      ┆ 573    ┆ ON     │
│         ┆ trucció ┆ ractac ┆ ó      ┆      ┆        ┆        ┆        ┆ mesos  ┆        ┆ HUARTE │
│         ┆ d'un    ┆ iopubl ┆        ┆      ┆        ┆        ┆        ┆ 0 dies ┆        ┆ LAIN,  │
│         ┆ edifici ┆ ica.ca ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆ SA     │
│         ┆ plurifa ┆ t/ca/d ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ miliar  ┆ etall- ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ de 53   ┆ public ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ habitat ┆ acio/8 ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ ges,    ┆ 29a590 ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ local   ┆ f-b087 ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ comerci ┆ -52b7- ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ al i    ┆ 66ee-0 ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ aparcam ┆ 74dcc3 ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ ent, al ┆ 444eb/ ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ carrer  ┆ 200141 ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Pare    ┆ 003    ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Perez   ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ del     ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Pulgar  ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 38 de   ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Barcelo ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ na (Tri ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ nitat   ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Vella   ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 18.01), ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ amb     ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ mesures ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ de cont ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ ractaci ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ ó       ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ pública ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ sosteni ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ ble     ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ (exp.   ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 23/013) ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│ 20/085  ┆ Obres   ┆ https: ┆ Formal ┆ 2020 ┆ 449543 ┆ 404777 ┆ Barcel ┆ 2 anys ┆ B58117 ┆ ROIG   │
│         ┆ de cons ┆ //cont ┆ itzaci ┆      ┆ 9.2    ┆ 8.12   ┆ ona    ┆ 2      ┆ 086    ┆ CONSTR │
│         ┆ trucció ┆ ractac ┆ ó      ┆      ┆        ┆        ┆        ┆ mesos  ┆        ┆ UCCION │
│         ┆ d'un    ┆ iopubl ┆        ┆      ┆        ┆        ┆        ┆ 0 dies ┆        ┆ ES Y   │
│         ┆ edifici ┆ ica.ca ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆ SERVIC │
│         ┆ plurifa ┆ t/ca/d ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆ IOS,   │
│         ┆ miliar  ┆ etall- ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆ SL     │
│         ┆ de 31   ┆ public ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ habitat ┆ acio/8 ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ ges, un ┆ 58746b ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ local   ┆ f-f92d ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ comerci ┆ -fba4- ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ al i    ┆ a3d5-e ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ urbanit ┆ dfa27a ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ zació a ┆ 9c3b9/ ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ l'aving ┆ 798733 ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ uda Esc ┆ 46     ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ olapi   ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Càncer  ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 27-33   ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ del     ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ barri   ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ de      ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Torre   ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Baró de ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Barcelo ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ na.     ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Exp.    ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 20/085  ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│ 455/202 ┆ Obres   ┆ https: ┆ Adjudi ┆ 2020 ┆ 24759. ┆ 16958. ┆ Barcel ┆ 0 anys ┆ B66963 ┆ MULTIS │
│ 0/CMENO ┆ de      ┆ //cont ┆ cació  ┆      ┆ 79     ┆ 64     ┆ ona    ┆ 1      ┆ 711    ┆ ERVEIS │
│ RS      ┆ reforma ┆ ractac ┆        ┆      ┆        ┆        ┆        ┆ mesos  ┆        ┆ NOU    │
│         ┆ pis 2n  ┆ iopubl ┆        ┆      ┆        ┆        ┆        ┆ 15     ┆        ┆ NET,   │
│         ┆ 1a del  ┆ ica.ca ┆        ┆      ┆        ┆        ┆        ┆ dies   ┆        ┆ S.L.   │
│         ┆ carrerv ┆ t/ca/d ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Conca,  ┆ etall- ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ al      ┆ public ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ barri   ┆ acio/8 ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ de La   ┆ fba97f ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Ribera, ┆ 6-0449 ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ de Mont ┆ -4c89- ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ cada i  ┆ 7f49-c ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Reixac  ┆ 96d3af ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆         ┆ c2053/ ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆         ┆ 711984 ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆         ┆ 55     ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│ X202300 ┆ L’objec ┆ https: ┆ Desert ┆ 2023 ┆ 2.0632 ┆ null   ┆ Palafo ┆ 2 anys ┆ null   ┆ null   │
│ 3753    ┆ te del  ┆ //cont ┆        ┆      ┆ e6     ┆        ┆ lls    ┆ 3      ┆        ┆        │
│         ┆ contrac ┆ ractac ┆        ┆      ┆        ┆        ┆        ┆ mesos  ┆        ┆        │
│         ┆ te      ┆ iopubl ┆        ┆      ┆        ┆        ┆        ┆ dies   ┆        ┆        │
│         ┆ versa   ┆ ica.ca ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ sobre   ┆ t/ca/d ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ les     ┆ etall- ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ obres   ┆ public ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ per a   ┆ acio/1 ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ la cons ┆ 14d6c0 ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ trucció ┆ 5-f05d ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ d’una   ┆ -4a68- ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ promoci ┆ 9a40-5 ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ ó munic ┆ 460bbc ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ ipal    ┆ 892f0/ ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ d’habit ┆ 200155 ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ atges   ┆ 751    ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ de prot ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ ecció   ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ oficial ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ i       ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ comprèn ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ també   ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ la reda ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ cció    ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ del seu ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ project ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ e, en   ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ els     ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ termes  ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ definit ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ s a l’a ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ vantpro ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ jecte   ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ incorpo ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ rat com ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ ANNEX 1 ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ (AVPJ). ┆        ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│ …       ┆ …       ┆ …      ┆ …      ┆ …    ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ 25/070  ┆ Obres   ┆ https: ┆ Adjudi ┆ 2025 ┆ 305564 ┆ 223944 ┆ Barcel ┆ 10     ┆ B65337 ┆ Teknif │
│         ┆ de      ┆ //cont ┆ cació  ┆      ┆ .32    ┆ .88    ┆ ona    ┆ mesos  ┆ 362    ┆ ika    │
│         ┆ reforma ┆ ractac ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆ Grup   │
│         ┆ interio ┆ iopubl ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆ SL     │
│         ┆ r de 5  ┆ ica.ca ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ habitat ┆ t/ca/d ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ ges amb ┆ etall- ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ canvi   ┆ public ┆        ┆      ┆        ┆        ┆        ┆        ┆        ┆        │

In [4]:
t = raw.group_by("status").agg([
    pl.len().alias("count")
])
t

shape: (5, 2)
┌───────────────┬───────┐
│ status        ┆ count │
│ ---           ┆ ---   │
│ str           ┆ u32   │
╞═══════════════╪═══════╡
│ Renúncia      ┆ 5     │
│ Formalització ┆ 191   │
│ Desisitment   ┆ 3     │
│ Adjudicació   ┆ 85    │
│ Desert        ┆ 19    │
└───────────────┴───────┘

In [5]:
mapa_numeros = {
    "Adjudicació": "8",
    "Formalització": "9",
    "Desert": "3",
    "Desisitment": "4",
    "Renúncia":"5"
}

for palabra, digito in mapa_numeros.items():
    raw = raw.with_columns(
        pl.col("status").str.replace_all(palabra, digito)
    )

In [6]:
mapa_numeros = {
    r"(?i)\buna?\b": "1",
    r"(?i)\bdos\b": "2",
    r"(?i)\btres\b": "3",
    r"(?i)\bquatre\b": "4",
    r"(?i)\bcinc\b": "5",
    r"(?i)\bsis\b": "6",
    r"(?i)\bset\b": "7",
    r"(?i)\bvuit\b": "8",
    r"(?i)\bnou\b": "9",
    r"(?i)\bdeu\b": "10"
}

pattern = r"(?i)(?:(\d+)\s*(?:HPO|VPP|habitatges?|allotjaments?|unifamiliars?|v\.)|(?:alojamientos?|viviendas?|unifamiliares?|v\.)\s*(\d+))"

v = raw.with_columns(
    pl.col("title").alias("title_clean")
)
for palabra, digito in mapa_numeros.items():
    v = v.with_columns(
        pl.col("title_clean").str.replace_all(palabra, digito)
    )

v = v.with_columns(
    pl.col("title_clean")
    .str.extract(pattern, 1)
    .fill_null(pl.col("title_clean").str.extract(pattern, 2))
    .cast(pl.Int32, strict=False)
    .alias("n_viviendas")
).drop("title_clean")
v

shape: (303, 12)
┌────────┬────────┬────────┬────────┬──────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┐
│ id     ┆ title  ┆ link_h ┆ status ┆ year ┆ estim ┆ payab ┆ city  ┆ durat ┆ cif_p ┆ name_ ┆ n_viv │
│ ---    ┆ ---    ┆ ref    ┆ ---    ┆ ---  ┆ atedA ┆ leAmo ┆ ---   ┆ ion   ┆ rovid ┆ provi ┆ ienda │
│ str    ┆ str    ┆ ---    ┆ str    ┆ i32  ┆ mount ┆ unt   ┆ str   ┆ ---   ┆ er    ┆ der   ┆ s     │
│        ┆        ┆ str    ┆        ┆      ┆ ---   ┆ ---   ┆       ┆ str   ┆ ---   ┆ ---   ┆ ---   │
│        ┆        ┆        ┆        ┆      ┆ f64   ┆ str   ┆       ┆       ┆ str   ┆ str   ┆ i32   │
╞════════╪════════╪════════╪════════╪══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╡
│ 202004 ┆ L'obje ┆ https: ┆ 9      ┆ 2022 ┆ 4.987 ┆ 500.0 ┆ Giron ┆ 75    ┆ B6289 ┆ VISOR ┆ null  │
│ 1499   ┆ cte    ┆ //cont ┆        ┆      ┆ 6e6   ┆ 0     ┆ a     ┆ anys  ┆ 0751  ┆ EN SL ┆       │
│        ┆ del    ┆ ractac ┆        ┆      ┆       ┆       ┆       ┆ 0     ┆       ┆       ┆       │
│        ┆ presen ┆ iopubl ┆        ┆      ┆       ┆       ┆       ┆ mesos ┆       ┆       ┆       │
│        ┆ t cont ┆ ica.ca ┆        ┆      ┆       ┆       ┆       ┆ 0     ┆       ┆       ┆       │
│        ┆ racte  ┆ t/ca/d ┆        ┆      ┆       ┆       ┆       ┆ dies  ┆       ┆       ┆       │
│        ┆ és la  ┆ etall- ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ transm ┆ public ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ issió  ┆ acio/c ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ oneros ┆ eb149b ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ a i    ┆ 8-1845 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ consti ┆ -3f0c- ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ tució  ┆ 8279-1 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ d'un   ┆ c8939e ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ dret   ┆ a0c3c/ ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ de sup ┆ 200024 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ erfíci ┆ 086    ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ e per  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ un ter ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ mini   ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ de 75  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ anys   ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ sobre  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ una    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ finca  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ de pro ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ pietat ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ de l'A ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ juntam ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ent de ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Girona ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ integr ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ada    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ dins   ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ el Pat ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ rimoni ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ munici ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ pal de ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Sòl i  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Habita ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ tge    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ situad ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ a al   ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ carrer ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Agudes ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 72-74  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ de Gir ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ona,   ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ amb    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ referè ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ncia   ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ cadast ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ral    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 366740 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 1DG843 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 6H0001 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ OM als ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ efecte ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ s de   ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ proced ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ir a   ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ la pro ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ moció, ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ constr ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ucció  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ i      ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ gestió ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ d'habi ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ tatges ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ de pr… ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ 23/013 ┆ Obres  ┆ https: ┆ 9      ┆ 2023 ┆ 1.456 ┆ 10836 ┆ Barce ┆ 2     ┆ A4801 ┆ OBRAS ┆ 53    │
│        ┆ de con ┆ //cont ┆        ┆      ┆ 3e7   ┆ 483.3 ┆ lona  ┆ anys  ┆ 0573  ┆ CON   ┆       │
│        ┆ strucc ┆ ractac ┆        ┆      ┆       ┆ 7     ┆       ┆ 8     ┆       ┆ HUART ┆       │
│        ┆ ió     ┆ iopubl ┆        ┆      ┆       ┆       ┆       ┆ mesos ┆       ┆ E     ┆       │
│        ┆ d'un   ┆ ica.ca ┆        ┆      ┆       ┆       ┆       ┆ 0     ┆       ┆ LAIN, ┆       │
│        ┆ edific ┆ t/ca/d ┆        ┆      ┆       ┆       ┆       ┆ dies  ┆       ┆ SA    ┆       │
│        ┆ i plur ┆ etall- ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ifamil ┆ public ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ iar de ┆ acio/8 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 53 hab ┆ 29a590 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ itatge ┆ f-b087 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ s,     ┆ -52b7- ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ local  ┆ 66ee-0 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ comerc ┆ 74dcc3 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ial i  ┆ 444eb/ ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ aparca ┆ 200141 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ment,  ┆ 003    ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ al     ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ carrer ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Pare   ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Perez  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ del    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Pulgar ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 38 de  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Barcel ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ona    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ (Trini ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ tat    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Vella  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 18.01) ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ , amb  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ mesure ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ s de   ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ contra ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ctació ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ públic ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ a sost ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ enible ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ (exp.  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 23/013 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ )      ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ 20/085 ┆ Obres  ┆ https: ┆ 9      ┆ 2020 ┆ 44954 ┆ 40477 ┆ Barce ┆ 2     ┆ B5811 ┆ ROIG  ┆ 31    │
│        ┆ de con ┆ //cont ┆        ┆      ┆ 39.2  ┆ 78.12 ┆ lona  ┆ anys  ┆ 7086  ┆ CONST ┆       │
│        ┆ strucc ┆ ractac ┆        ┆      ┆       ┆       ┆       ┆ 2     ┆       ┆ RUCCI ┆       │
│        ┆ ió     ┆ iopubl ┆        ┆      ┆       ┆       ┆       ┆ mesos ┆       ┆ ONES  ┆       │
│        ┆ d'un   ┆ ica.ca ┆        ┆      ┆       ┆       ┆       ┆ 0     ┆       ┆ Y SER ┆       │
│        ┆ edific ┆ t/ca/d ┆        ┆      ┆       ┆       ┆       ┆ dies  ┆       ┆ VICIO ┆       │
│        ┆ i plur ┆ etall- ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ S, SL ┆       │
│        ┆ ifamil ┆ public ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ iar de ┆ acio/8 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 31 hab ┆ 58746b ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ itatge ┆ f-f92d ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ s, un  ┆ -fba4- ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ local  ┆ a3d5-e ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ comerc ┆ dfa27a ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ial i  ┆ 9c3b9/ ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ urbani ┆ 798733 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ tzació ┆ 46     ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ a l'av ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ inguda ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Escola ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ pi     ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Càncer ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 27-33  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ del    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ barri  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ de     ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Torre  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Baró   ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ de Bar ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ celona ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ . Exp. ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 20/085 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ 455/20 ┆ Obres  ┆ https: ┆ 8      ┆ 2020 ┆ 24759 ┆ 16958 ┆ Barce ┆ 0     ┆ B6696 ┆ MULTI ┆ null  │
│ 20/CME ┆ de ref ┆ //cont ┆        ┆      ┆ .79   ┆ .64   ┆ lona  ┆ anys  ┆ 3711  ┆ SERVE ┆       │
│ NORS   ┆ orma   ┆ ractac ┆        ┆      ┆       ┆       ┆       ┆ 1     ┆       ┆ IS    ┆       │
│        ┆ pis 2n ┆ iopubl ┆        ┆      ┆       ┆       ┆       ┆ mesos ┆       ┆ NOU   ┆       │
│        ┆ 1a del ┆ ica.ca ┆        ┆      ┆       ┆       ┆       ┆ 15    ┆       ┆ NET,  ┆       │
│        ┆ carrer ┆ t/ca/d ┆        ┆      ┆       ┆       ┆       ┆ dies  ┆       ┆ S.L.  ┆       │
│        ┆ vConca ┆ etall- ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ , al   ┆ public ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ barri  ┆ acio/8 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ de La  ┆ fba97f ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Ribera ┆ 6-0449 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ , de   ┆ -4c89- ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Montca ┆ 7f49-c ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ da i   ┆ 96d3af ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Reixac ┆ c2053/ ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆        ┆ 711984 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆        ┆ 55     ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ X20230 ┆ L’obje ┆ https: ┆ 3      ┆ 2023 ┆ 2.063 ┆ null  ┆ Palaf ┆ 2     ┆ null  ┆ null  ┆ null  │
│ 03753  ┆ cte    ┆ //cont ┆        ┆      ┆ 2e6   ┆       ┆ olls  ┆ anys  ┆       ┆       ┆       │
│        ┆ del    ┆ ractac ┆        ┆      ┆       ┆       ┆       ┆ 3     ┆       ┆       ┆       │
│        ┆ contra ┆ iopubl ┆        ┆      ┆       ┆       ┆       ┆ mesos ┆       ┆       ┆       │
│        ┆ cte    ┆ ica.ca ┆        ┆      ┆       ┆       ┆       ┆ dies  ┆       ┆       ┆       │
│        ┆ versa  ┆ t/ca/d ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ sobre  ┆ etall- ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ les    ┆ public ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ obres  ┆ acio/1 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ per a  ┆ 14d6c0 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ la con ┆ 5-f05d ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ strucc ┆ -4a68- ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ió     ┆ 9a40-5 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ d’una  ┆ 460bbc ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ promoc ┆ 892f0/ ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ió mun ┆ 200155 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ icipal ┆ 751    ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ d’habi ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ tatges ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ de pro ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ tecció ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ oficia ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ l i    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ comprè ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ n      ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ també  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ la red ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ acció  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ del    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ seu    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │

In [11]:
f = v.with_columns(
    (
        pl.col("duration").str.extract(r"(\d+)", 1).cast(pl.Int64) * 365 +
        pl.col("duration").str.extract(r"\d+\D+(\d+)", 1).cast(pl.Int64) * 30 +
        pl.col("duration").str.extract(r"\d+\D+\d+\D+(\d+)", 1).cast(pl.Int64)
    ),
        pl.col("status").cast(pl.Int64),
        pl.col("payableAmount").str.split("||").list.get(0).cast(pl.Float64)
)
f

shape: (303, 12)
┌────────┬────────┬────────┬────────┬──────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┐
│ id     ┆ title  ┆ link_h ┆ status ┆ year ┆ estim ┆ payab ┆ city  ┆ durat ┆ cif_p ┆ name_ ┆ n_viv │
│ ---    ┆ ---    ┆ ref    ┆ ---    ┆ ---  ┆ atedA ┆ leAmo ┆ ---   ┆ ion   ┆ rovid ┆ provi ┆ ienda │
│ str    ┆ str    ┆ ---    ┆ i64    ┆ i32  ┆ mount ┆ unt   ┆ str   ┆ ---   ┆ er    ┆ der   ┆ s     │
│        ┆        ┆ str    ┆        ┆      ┆ ---   ┆ ---   ┆       ┆ i64   ┆ ---   ┆ ---   ┆ ---   │
│        ┆        ┆        ┆        ┆      ┆ f64   ┆ f64   ┆       ┆       ┆ str   ┆ str   ┆ i32   │
╞════════╪════════╪════════╪════════╪══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╡
│ 202004 ┆ L'obje ┆ https: ┆ 9      ┆ 2022 ┆ 4.987 ┆ 500.0 ┆ Giron ┆ 27375 ┆ B6289 ┆ VISOR ┆ null  │
│ 1499   ┆ cte    ┆ //cont ┆        ┆      ┆ 6e6   ┆       ┆ a     ┆       ┆ 0751  ┆ EN SL ┆       │
│        ┆ del    ┆ ractac ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ presen ┆ iopubl ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ t cont ┆ ica.ca ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ racte  ┆ t/ca/d ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ és la  ┆ etall- ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ transm ┆ public ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ issió  ┆ acio/c ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ oneros ┆ eb149b ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ a i    ┆ 8-1845 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ consti ┆ -3f0c- ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ tució  ┆ 8279-1 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ d'un   ┆ c8939e ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ dret   ┆ a0c3c/ ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ de sup ┆ 200024 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ erfíci ┆ 086    ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ e per  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ un ter ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ mini   ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ de 75  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ anys   ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ sobre  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ una    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ finca  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ de pro ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ pietat ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ de l'A ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ juntam ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ent de ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Girona ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ integr ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ada    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ dins   ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ el Pat ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ rimoni ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ munici ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ pal de ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Sòl i  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Habita ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ tge    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ situad ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ a al   ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ carrer ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Agudes ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 72-74  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ de Gir ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ona,   ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ amb    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ referè ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ncia   ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ cadast ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ral    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 366740 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 1DG843 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 6H0001 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ OM als ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ efecte ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ s de   ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ proced ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ir a   ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ la pro ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ moció, ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ constr ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ucció  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ i      ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ gestió ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ d'habi ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ tatges ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ de pr… ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ 23/013 ┆ Obres  ┆ https: ┆ 9      ┆ 2023 ┆ 1.456 ┆ 1.083 ┆ Barce ┆ 970   ┆ A4801 ┆ OBRAS ┆ 53    │
│        ┆ de con ┆ //cont ┆        ┆      ┆ 3e7   ┆ 6e7   ┆ lona  ┆       ┆ 0573  ┆ CON   ┆       │
│        ┆ strucc ┆ ractac ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ HUART ┆       │
│        ┆ ió     ┆ iopubl ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ E     ┆       │
│        ┆ d'un   ┆ ica.ca ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ LAIN, ┆       │
│        ┆ edific ┆ t/ca/d ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ SA    ┆       │
│        ┆ i plur ┆ etall- ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ifamil ┆ public ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ iar de ┆ acio/8 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 53 hab ┆ 29a590 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ itatge ┆ f-b087 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ s,     ┆ -52b7- ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ local  ┆ 66ee-0 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ comerc ┆ 74dcc3 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ial i  ┆ 444eb/ ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ aparca ┆ 200141 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ment,  ┆ 003    ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ al     ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ carrer ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Pare   ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Perez  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ del    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Pulgar ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 38 de  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Barcel ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ona    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ (Trini ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ tat    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Vella  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 18.01) ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ , amb  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ mesure ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ s de   ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ contra ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ctació ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ públic ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ a sost ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ enible ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ (exp.  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 23/013 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ )      ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ 20/085 ┆ Obres  ┆ https: ┆ 9      ┆ 2020 ┆ 44954 ┆ 4.047 ┆ Barce ┆ 790   ┆ B5811 ┆ ROIG  ┆ 31    │
│        ┆ de con ┆ //cont ┆        ┆      ┆ 39.2  ┆ 8e6   ┆ lona  ┆       ┆ 7086  ┆ CONST ┆       │
│        ┆ strucc ┆ ractac ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ RUCCI ┆       │
│        ┆ ió     ┆ iopubl ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ ONES  ┆       │
│        ┆ d'un   ┆ ica.ca ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ Y SER ┆       │
│        ┆ edific ┆ t/ca/d ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ VICIO ┆       │
│        ┆ i plur ┆ etall- ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ S, SL ┆       │
│        ┆ ifamil ┆ public ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ iar de ┆ acio/8 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 31 hab ┆ 58746b ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ itatge ┆ f-f92d ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ s, un  ┆ -fba4- ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ local  ┆ a3d5-e ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ comerc ┆ dfa27a ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ial i  ┆ 9c3b9/ ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ urbani ┆ 798733 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ tzació ┆ 46     ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ a l'av ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ inguda ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Escola ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ pi     ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Càncer ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 27-33  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ del    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ barri  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ de     ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Torre  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Baró   ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ de Bar ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ celona ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ . Exp. ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 20/085 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ 455/20 ┆ Obres  ┆ https: ┆ 8      ┆ 2020 ┆ 24759 ┆ 16958 ┆ Barce ┆ 45    ┆ B6696 ┆ MULTI ┆ null  │
│ 20/CME ┆ de ref ┆ //cont ┆        ┆      ┆ .79   ┆ .64   ┆ lona  ┆       ┆ 3711  ┆ SERVE ┆       │
│ NORS   ┆ orma   ┆ ractac ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ IS    ┆       │
│        ┆ pis 2n ┆ iopubl ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ NOU   ┆       │
│        ┆ 1a del ┆ ica.ca ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ NET,  ┆       │
│        ┆ carrer ┆ t/ca/d ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ S.L.  ┆       │
│        ┆ vConca ┆ etall- ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ , al   ┆ public ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ barri  ┆ acio/8 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ de La  ┆ fba97f ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Ribera ┆ 6-0449 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ , de   ┆ -4c89- ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Montca ┆ 7f49-c ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ da i   ┆ 96d3af ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ Reixac ┆ c2053/ ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆        ┆ 711984 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆        ┆ 55     ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ X20230 ┆ L’obje ┆ https: ┆ 3      ┆ 2023 ┆ 2.063 ┆ null  ┆ Palaf ┆ null  ┆ null  ┆ null  ┆ null  │
│ 03753  ┆ cte    ┆ //cont ┆        ┆      ┆ 2e6   ┆       ┆ olls  ┆       ┆       ┆       ┆       │
│        ┆ del    ┆ ractac ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ contra ┆ iopubl ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ cte    ┆ ica.ca ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ versa  ┆ t/ca/d ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ sobre  ┆ etall- ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ les    ┆ public ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ obres  ┆ acio/1 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ per a  ┆ 14d6c0 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ la con ┆ 5-f05d ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ strucc ┆ -4a68- ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ió     ┆ 9a40-5 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ d’una  ┆ 460bbc ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ promoc ┆ 892f0/ ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ ió mun ┆ 200155 ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ icipal ┆ 751    ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ d’habi ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ tatges ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ de pro ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ tecció ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ oficia ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ l i    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ comprè ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ n      ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ també  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ la red ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ acció  ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ del    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ seu    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │

In [ ]:
city = raw.group_by("city").agg([
    pl.len().alias("count")
]).sort(by="count", descending=True)
city

In [ ]:
total = pl.read_csv("/Users/machine/Documents/projects/vivienda/my-app/src/lib/components/datos/test.csv").drop(["organo", "PostalCode"])
final = pl.concat([total,f], how="vertical_relaxed")
final.write_csv("/Users/machine/Documents/projects/vivienda/my-app/src/lib/components/datos/test.csv")

In [38]:
sorted = final.sort(by="status", descending=True)
sorted.write_json("/Users/machine/Documents/projects/vivienda/my-app/src/lib/components/datos/test.json")

In [36]:
ranking = final.group_by("city").agg(
    pl.len()
).sort("len", descending=True)
ranking

shape: (271, 2)
┌───────────────────────┬─────┐
│ city                  ┆ len │
│ ---                   ┆ --- │
│ str                   ┆ u32 │
╞═══════════════════════╪═════╡
│ Barcelona             ┆ 170 │
│ Valladolid            ┆ 169 │
│ Mérida                ┆ 91  │
│ Tarragona             ┆ 53  │
│ Madrid                ┆ 41  │
│ Palma                 ┆ 30  │
│ València              ┆ 26  │
│ Tenerife              ┆ 25  │
│ Zaragoza              ┆ 24  │
│ Córdoba               ┆ 23  │
│ …                     ┆ …   │
│ Castielfabib          ┆ 1   │
│ Dos Hermanas          ┆ 1   │
│ Arasan                ┆ 1   │
│ Leganés               ┆ 1   │
│ Ondara                ┆ 1   │
│ Caracabuey            ┆ 1   │
│ Tramacastilla De Tena ┆ 1   │
│ Móstoles              ┆ 1   │
│ Utiel                 ┆ 1   │
│ Catalunya             ┆ 1   │
└───────────────────────┴─────┘