In [2]:
import polars as pl
import glob
from pathlib import Path
import polars.selectors as cs
pl.Config.set_tbl_cols(300).set_fmt_str_lengths(100).set_tbl_rows(30)

polars.config.Config

In [3]:
df_total = pl.read_parquet("../data/raw_data/*.parquet")

In [4]:
def netejar_noms(df):
    nous_noms = []
    vistos = {}

    for col in df.columns:
        nou_nom = col.split('.')[-1]
        
        #Si ja existeix, li posem un número (ex: ID_1, ID_2)
        if nou_nom in vistos:
            vistos[nou_nom] += 1
            nou_nom = f"{nou_nom}_{vistos[nou_nom]}"
        else:
            vistos[nou_nom] = 0
            
        nous_noms.append(nou_nom)
    df.columns = nous_noms
    return df

df_final = netejar_noms(df_total)

In [5]:
len(df_final)

3656443

In [6]:
selected_cols = [
    "id",
    "link_href",
    "summary",
    "title",
    "ContractFolderID",
    "ContractFolderStatusCode",
    "ContractingPartyTypeCode",
    "ContractingPartyTypeCode_listURI",
    "ID",
    "Name",
    "CityName",
    "PostalZone",
    "Line",
    "IdentificationCode",
    "Name_2",
    "Telephone",
    "ElectronicMail",
    "Name_3",
    "TypeCode",
    "TypeCode_listURI",
    "SubTypeCode",
    "SubTypeCode_listURI",
    "EstimatedOverallContractAmount",
    "TotalAmount",
    "TaxExclusiveAmount",
    "ItemClassificationCode",
    "CountrySubentityCode",
    "DurationMeasure",
    "DurationMeasure_unitCode",
    "OptionsDescription",
    "ResultCode",
    "ResultCode_listURI",
    "Name_4",
    "TotalAmount_1",
    "TaxExclusiveAmount_1",
    "ItemClassificationCode_1",
    "Description",
    "AwardDate",
    "IssueDate",
    "ID_2",
    "Name_5",
    "TaxExclusiveAmount_2",
    "PayableAmount",
    "EvaluationCriteriaTypeCode_1",
    "EvaluationCriteriaTypeCode_listURI_1",
    "EndDate",
    "EndDate_1",
    "URI_1",
    "Name_6",
    "FundingProgramCode",
    "FundingProgramCode_listURI",
    "URI_4"
]
df_c = df_final.select(selected_cols).unique()
len(df_c)

2475327

In [7]:
dic = pl.read_excel("../data/raw_data/cpv_2008_ver_2013.xlsx").with_columns(
    pl.col("CODE").str.replace_all(r"(-\d{1})", "")
)

In [8]:
df_with_codes = df_c.join(
    dic,
    left_on="ItemClassificationCode" ,
    right_on="CODE",
    how="inner"
)

In [9]:
df_with_codes.write_csv("../data/licitaciones_2012-2026.csv")

In [10]:
df_with_codes.height

2455610

In [11]:
# Què cal fer ara? Ara hem de buscar els codis CVP per determinar quines 
# licitacions son de construcció de vivenda, la que sigui, si? 

code_houseing = ["45211200", "45211000", "45211100", "45211300", "45211340"]

df_construccion = df_with_codes.filter(
    pl.col("ItemClassificationCode").str.starts_with(code_houseing[0]) |
    pl.col("ItemClassificationCode").str.starts_with(code_houseing[1]) |
    pl.col("ItemClassificationCode").str.starts_with(code_houseing[2]) |
    pl.col("ItemClassificationCode").str.starts_with(code_houseing[3]) |
    pl.col("ItemClassificationCode").str.starts_with(code_houseing[4]) 
)

df_construccion["ItemClassificationCode"].value_counts(sort=True).write_csv("../data/clean_data/construction_codes.csv")

In [12]:
len(df_construccion)

3489

In [13]:
df_construccion["ItemClassificationCode"].value_counts(sort=True).write_csv("../data/clean_data/construction_codes.csv")

In [14]:
t = df_construccion.filter(
    (pl.col("ContractFolderStatusCode") == "RES")
)
len(t)

1107

In [15]:
c = t.filter(
    (pl.col("DurationMeasure").is_not_null()) &
    (pl.col("DurationMeasure_unitCode").is_not_null())
).with_columns(
    pl.when(
        (pl.col("DurationMeasure_unitCode") == "ANN") 
    ).then(
        pl.col("DurationMeasure").cast(pl.Int32) * 365
    ).when(
        (pl.col("DurationMeasure_unitCode") == "MON")
    ).then(
        pl.col("DurationMeasure").cast(pl.Int32) * 30
    ).otherwise(
        pl.col("DurationMeasure").cast(pl.Int32)
    ), 
    pl.when(
        (pl.col("DurationMeasure_unitCode") == "ANN") | (pl.col("DurationMeasure_unitCode") == "MON")
    ).then(
        pl.lit("DAY")
    ).otherwise(
        pl.col("DurationMeasure_unitCode")
    ).alias("DurationMeasure_unitCode")
)

In [16]:
len(c)

1074

In [17]:
promotoras = c.group_by("ID_2").agg([
    pl.len().alias("count")
]).sort(by="count", descending=True)
promotoras

shape: (466, 2)
┌───────────┬───────┐
│ ID_2      ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ null      ┆ 184   │
│ B35543958 ┆ 13    │
│ B10103208 ┆ 12    │
│ B06434641 ┆ 12    │
│ B05163589 ┆ 12    │
│ B05246400 ┆ 11    │
│ A73998346 ┆ 10    │
│ A33615931 ┆ 10    │
│ B05244066 ┆ 9     │
│ B54342142 ┆ 9     │
│ A50070663 ┆ 9     │
│ A28019206 ┆ 8     │
│ B86783628 ┆ 8     │
│ B06617187 ┆ 8     │
│ A84465749 ┆ 7     │
│ …         ┆ …     │
│ B10473130 ┆ 1     │
│ B25547308 ┆ 1     │
│ b13516463 ┆ 1     │
│ B35897610 ┆ 1     │
│ B76664457 ┆ 1     │
│ B21837331 ┆ 1     │
│ B24285645 ┆ 1     │
│ B05455522 ┆ 1     │
│ 92272     ┆ 1     │
│ B30901821 ┆ 1     │
│ B53206504 ┆ 1     │
│ B14517239 ┆ 1     │
│ B98588924 ┆ 1     │
│ B13454061 ┆ 1     │
│ 09417233K ┆ 1     │
└───────────┴───────┘

In [18]:
status_result = c.group_by("ResultCode").agg([
    pl.len().alias("count")
]).sort(by="count", descending=True)
status_result

shape: (5, 2)
┌────────────┬───────┐
│ ResultCode ┆ count │
│ ---        ┆ ---   │
│ str        ┆ u32   │
╞════════════╪═══════╡
│ 9          ┆ 496   │
│ 8          ┆ 386   │
│ 3          ┆ 174   │
│ 4          ┆ 17    │
│ 5          ┆ 1     │
└────────────┴───────┘

In [19]:
admin_level = c.group_by("ContractingPartyTypeCode").agg([pl.len().alias("count")
]).sort(by="count", descending=True)
admin_level

shape: (10, 2)
┌──────────────────────────┬───────┐
│ ContractingPartyTypeCode ┆ count │
│ ---                      ┆ ---   │
│ str                      ┆ u32   │
╞══════════════════════════╪═══════╡
│ 3                        ┆ 363   │
│ 2                        ┆ 358   │
│ 5                        ┆ 176   │
│ 8                        ┆ 77    │
│ 1                        ┆ 26    │
│ 11                       ┆ 24    │
│ 7                        ┆ 22    │
│ 10                       ┆ 14    │
│ 4                        ┆ 8     │
│ 6                        ┆ 6     │
└──────────────────────────┴───────┘

In [20]:
places = c.group_by("CityName").agg([pl.len().alias("count")
]).sort(by="count", descending=True)
places

shape: (222, 2)
┌────────────────────────────┬───────┐
│ CityName                   ┆ count │
│ ---                        ┆ ---   │
│ str                        ┆ u32   │
╞════════════════════════════╪═══════╡
│ Valladolid                 ┆ 175   │
│ Mérida                     ┆ 120   │
│ Madrid                     ┆ 100   │
│ Palma                      ┆ 35    │
│ Málaga                     ┆ 31    │
│ València                   ┆ 31    │
│ Zaragoza                   ┆ 29    │
│ Cáceres                    ┆ 26    │
│ Valencia                   ┆ 25    │
│ Santa Cruz de Tenerife     ┆ 25    │
│ Córdoba                    ┆ 23    │
│ Las Palmas de Gran Canaria ┆ 19    │
│ Toledo                     ┆ 18    │
│ Almería                    ┆ 16    │
│ Oviedo                     ┆ 14    │
│ …                          ┆ …     │
│ Paterna del Río            ┆ 1     │
│ Villalba del Rey  (Cuenca) ┆ 1     │
│ Oliete                     ┆ 1     │
│ Burbaguena                 ┆ 1     │
│ Dos Hermanas               ┆ 1     │
│ Pozuelo de Alarcón         ┆ 1     │
│ Estada                     ┆ 1     │
│ Vilamarxant                ┆ 1     │
│ Vilafamés                  ┆ 1     │
│ Puebla de Guzmán           ┆ 1     │
│ Cualedro                   ┆ 1     │
│ Sagunto                    ┆ 1     │
│ Mieza                      ┆ 1     │
│ Puebla de Don Fadrique     ┆ 1     │
│ Almassora                  ┆ 1     │
└────────────────────────────┴───────┘

In [21]:
print(c["title"])

shape: (1_074,)
Series: 'title' [str]
[
	"vp-VA. Obras de ejecución de acondicionamiento de vivienda c/ El Plantío nº 6, 2º B, Pedrajas de San…
	"Obras de reforma y mejora de la eficiencia energética del Grupo de Viviendas VPP-PD “La Fresneda”, e…
	"Contrato de Obras de Rehabilitación Energética de 30 Viviendas en la calle Alcántara de Mérida y de …
	"construcción 10 VPO en plan parcial R2"
	"Proyecto de ejecución y estudio de seguridad y salud de obras de reparación de cubiertas en Avenida …
	"Acondicionamientos de Viviendas en Almendralejo (Badajoz) - 5 Lotes"
	"Obras para la terminación de la edificación de 39 viviendas con protección pública en alquiler, 42 g…
	"Rehabilitación das antigas vivendas dos mestres, Rúa Eduardo Blanco Amor, 10, Referencias Catastrais…
	"Construcción de un edificio piloto, de 18 viviendas de promoción pública sostenibles e innovadoras, …
	"Obras varias de reforma en el Palacio de la Capitanía General"
	"Edificio plurifamiliar para 64 VPO, locales, trasteros y garajes en la parcela VPR 2.4.1 de la UE CS…
	"Rehabilitación edificio para peluquería, sala de fisioterapia y vivienda nuevos pobladores."
	"FON COH TER-SG-Rehabilitación de vivienda para alquiler social en C/Primo de Rivera, nº 15 de VALDEL…
	"Construcción de tres viviendas municipales en edificio plurifamiliar en C/ Andalucía nº 7 esquina co…
	"FON COH TER-BU-Obra de rehabilitación inmueble de una vivienda para alquiler social en Plaza de la V…
	…
	"Ejecución de pintura plástica con propiedades térmicas en c/ GARZA 3 Y 9, y suministro e instalación…
	"Obras de construcción de la promoción denominada Cañaveral 7, Distrito de Vicálvaro, Madrid"
	"Obras de puesta en uso de 7 viviendas del Patronato"
	"Obras de construcción  de 8 viviendas unifamiliares de Protección Oficial en calles San Isidro, San …
	"Obras de construcción de 29 viviendas de promoción pública en alquiler social en edificio energética…
	"Construcción de 4 VPP en Portaje"
	"Obra de construcción de 3 viviendas adosadas protegidas en régimen de alquiler en la C/ Romero nº 3 …
	"Obras de construcción de la Promoción denominada “Cañaveral 03”, situada en el Distrito de Vicálvaro…
	"Obras de construcción de 24 viviendas protegidas, aparcamientos, trasteros y locales en la parcela R…
	"Expte. 0064/2019 «Reforma y acondicionamiento de tres viviendas de titularidad municipal»"
	"Contrato de obras de Rehabilitación de vivendas en Caldelas, de titularidade do Concello de Tui para…
	"Construcción de un edificio de veinticinco alojamientos dotacionales en Palma (Mallorca)"
	"Obras de construcción de 25 viviendas de VPO, en la parcela 1.2.12 en Prados de Torrejón"
	"Construcción de apartamento en 1ª planta del Centro Social de Espés"
	"Contrato de Obras de Rehabilitación de un edificio existente para la construcción de viviendas en al…
]

In [22]:
mapa_numeros = {
    r"(?i)\buna?\b": "1",
    r"(?i)\bdos\b": "2",
    r"(?i)\btres\b": "3",
    r"(?i)\bcuatro\b": "4",
    r"(?i)\bcinco\b": "5",
    r"(?i)\bseis\b": "6",
    r"(?i)\bsiete\b": "7",
    r"(?i)\bocho\b": "8",
    r"(?i)\bnueve\b": "9",
    r"(?i)\bdiez\b": "10"
}

pattern = r"(?i)(?:(\d+)\s*(?:VPO|VPP|alojamientos?|viviendas?|unifamiliares?|v\.)|(?:VPO|VPP|alojamientos?|viviendas?|unifamiliares?|v\.)\s*(\d+))"
v = c.with_columns(
    pl.col("title").alias("title_clean")
)

for palabra, digito in mapa_numeros.items():
    v = v.with_columns(
        pl.col("title_clean").str.replace_all(palabra, digito)
    )

v = v.with_columns(
    pl.col("title_clean")
    .str.extract(pattern, 1)
    .fill_null(pl.col("title_clean").str.extract(pattern, 2))
    .cast(pl.Int32, strict=False)
    .alias("n_viviendas")
).drop("title_clean")

In [23]:
df_by_year = v.with_columns(
    pl.col("AwardDate").str.extract(r"\d{4}", 0).alias("year")
)

# .group_by("year").agg([
#    pl.len().alias("n_tenders")
# ]).sort(by="year", descending=True)
df_by_year

shape: (1_074, 55)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ id  ┆ lin ┆ sum ┆ tit ┆ Con ┆ Con ┆ Con ┆ Con ┆ ID  ┆ Nam ┆ Cit ┆ Pos ┆ Lin ┆ Ide ┆ Nam ┆ Tel ┆ Ele ┆ Nam ┆ Typ ┆ Typ ┆ Sub ┆ Sub ┆ Est ┆ Tot ┆ Tax ┆ Ite ┆ Cou ┆ Dur ┆ Dur ┆ Opt ┆ Res ┆ Res ┆ Nam ┆ Tot ┆ Tax ┆ Ite ┆ Des ┆ Awa ┆ Iss ┆ ID_ ┆ Nam ┆ Tax ┆ Pay ┆ Eva ┆ Eva ┆ End ┆ End ┆ URI ┆ Nam ┆ Fun ┆ Fun ┆ URI ┆ ES  ┆ n_v ┆ yea │
│ --- ┆ k_h ┆ mar ┆ le  ┆ tra ┆ tra ┆ tra ┆ tra ┆ --- ┆ e   ┆ yNa ┆ tal ┆ e   ┆ nti ┆ e_2 ┆ eph ┆ ctr ┆ e_3 ┆ eCo ┆ eCo ┆ Typ ┆ Typ ┆ ima ┆ alA ┆ Exc ┆ mCl ┆ ntr ┆ ati ┆ ati ┆ ion ┆ ult ┆ ult ┆ e_4 ┆ alA ┆ Exc ┆ mCl ┆ cri ┆ rdD ┆ ueD ┆ 2   ┆ e_5 ┆ Exc ┆ abl ┆ lua ┆ lua ┆ Dat ┆ Dat ┆ _1  ┆ e_6 ┆ din ┆ din ┆ _4  ┆ --- ┆ ivi ┆ r   │
│ str ┆ ref ┆ y   ┆ --- ┆ ctF ┆ ctF ┆ cti ┆ cti ┆ str ┆ --- ┆ me  ┆ Zon ┆ --- ┆ fic ┆ --- ┆ one ┆ oni ┆ --- ┆ de  ┆ de_ ┆ eCo ┆ eCo ┆ ted ┆ mou ┆ lus ┆ ass ┆ ySu ┆ onM ┆ onM ┆ sDe ┆ Cod ┆ Cod ┆ --- ┆ mou ┆ lus ┆ ass ┆ pti ┆ ate ┆ ate ┆ --- ┆ --- ┆ lus ┆ eAm ┆ tio ┆ tio ┆ e   ┆ e_1 ┆ --- ┆ --- ┆ gPr ┆ gPr ┆ --- ┆ str ┆ end ┆ --- │
│     ┆ --- ┆ --- ┆ str ┆ old ┆ old ┆ ngP ┆ ngP ┆     ┆ str ┆ --- ┆ e   ┆ str ┆ ati ┆ str ┆ --- ┆ cMa ┆ str ┆ --- ┆ lis ┆ de  ┆ de_ ┆ Ove ┆ nt  ┆ ive ┆ ifi ┆ ben ┆ eas ┆ eas ┆ scr ┆ e   ┆ e_l ┆ str ┆ nt_ ┆ ive ┆ ifi ┆ on  ┆ --- ┆ --- ┆ str ┆ str ┆ ive ┆ oun ┆ nCr ┆ nCr ┆ --- ┆ --- ┆ str ┆ str ┆ ogr ┆ ogr ┆ str ┆     ┆ as  ┆ str │
│     ┆ str ┆ str ┆     ┆ erI ┆ erS ┆ art ┆ art ┆     ┆     ┆ str ┆ --- ┆     ┆ onC ┆     ┆ str ┆ il  ┆     ┆ str ┆ tUR ┆ --- ┆ lis ┆ ral ┆ --- ┆ Amo ┆ cat ┆ tit ┆ ure ┆ ure ┆ ipt ┆ --- ┆ ist ┆     ┆ 1   ┆ Amo ┆ cat ┆ --- ┆ str ┆ str ┆     ┆     ┆ Amo ┆ t   ┆ ite ┆ ite ┆ str ┆ str ┆     ┆     ┆ amC ┆ amC ┆     ┆     ┆ --- ┆     │
│     ┆     ┆     ┆     ┆ D   ┆ tat ┆ yTy ┆ yTy ┆     ┆     ┆     ┆ str ┆     ┆ ode ┆     ┆     ┆ --- ┆     ┆     ┆ I   ┆ str ┆ tUR ┆ lCo ┆ str ┆ unt ┆ ion ┆ yCo ┆ --- ┆ _un ┆ ion ┆ str ┆ URI ┆     ┆ --- ┆ unt ┆ ion ┆ str ┆     ┆     ┆     ┆     ┆ unt ┆ --- ┆ ria ┆ ria ┆     ┆     ┆     ┆     ┆ ode ┆ ode ┆     ┆     ┆ i32 ┆     │
│     ┆     ┆     ┆     ┆ --- ┆ usC ┆ peC ┆ peC ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆ I   ┆ ntr ┆     ┆ --- ┆ Cod ┆ de  ┆ i32 ┆ itC ┆ --- ┆     ┆ --- ┆     ┆ str ┆ _1  ┆ Cod ┆     ┆     ┆     ┆     ┆     ┆ _2  ┆ str ┆ Typ ┆ Typ ┆     ┆     ┆     ┆     ┆ --- ┆ _li ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆ ode ┆ ode ┆ ode ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ act ┆     ┆ str ┆ e   ┆ --- ┆     ┆ ode ┆ str ┆     ┆ str ┆     ┆     ┆ --- ┆ e_1 ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ eCo ┆ eCo ┆     ┆     ┆     ┆     ┆ str ┆ stU ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ _li ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ Amo ┆     ┆     ┆ --- ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ de_ ┆ de_ ┆     ┆     ┆     ┆     ┆     ┆ RI  ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ stU ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ unt ┆     ┆     ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ lis ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RI  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ tUR ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ I_1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ htt ┆ htt ┆ Id  ┆ vp- ┆ A20 ┆ RES ┆ 2   ┆ htt ┆ 210 ┆ Con ┆ Val ┆ 470 ┆ Cal ┆ ES  ┆ Con ┆ 983 ┆ sco ┆ vp- ┆ 3   ┆ htt ┆ 452 ┆ htt ┆ 725 ┆ 878 ┆ 725 ┆ 452 ┆ ES4 ┆ 180 ┆ DAY ┆ nul ┆ 9   ┆ htt ┆ nul ┆ nul ┆ nul ┆ nul ┆ Ofe ┆ 202 ┆ 202 ┆ B06 ┆ MER ┆ 725 ┆ 878 ┆ nul ┆ nul ┆ 202 ┆ 202 ┆ htt ┆ Cas ┆ NO- ┆ htt ┆ htt ┆ Tra ┆ nul ┆ 202 │
│ ps: ┆ ps: ┆ lic ┆ VA. ┆ 25/ ┆     ┆     ┆ p:/ ┆ 383 ┆ sej ┆ lad ┆ 14  ┆ le  ┆     ┆ sej ┆ 419 ┆ ad. ┆ VA. ┆     ┆ p:/ ┆ 0   ┆ p:/ ┆ 90  ┆ 33. ┆ 90  ┆ 110 ┆ 18  ┆     ┆     ┆ l   ┆     ┆ p:/ ┆ l   ┆ l   ┆ l   ┆ l   ┆ rta ┆ 5-0 ┆ 5-1 ┆ 909 ┆ AKI ┆ 90  ┆ 33. ┆ l   ┆ l   ┆ 5-0 ┆ 5-0 ┆ ps: ┆ til ┆ EU  ┆ p:/ ┆ ps: ┆ baj ┆ l   ┆ 5   │
│ //c ┆ //c ┆ ita ┆ Obr ┆ 010 ┆     ┆     ┆ /co ┆ 701 ┆ erí ┆ oli ┆     ┆ Rig ┆     ┆ erí ┆ 000 ┆ mvo ┆ Obr ┆     ┆ /co ┆     ┆ /co ┆     ┆ 9   ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆ /co ┆     ┆     ┆     ┆     ┆ con ┆ 9-2 ┆ 0-0 ┆ 501 ┆ CR  ┆     ┆ 9   ┆     ┆     ┆ 7-3 ┆ 7-3 ┆ //c ┆ la  ┆     ┆ /co ┆ //c ┆ os  ┆     ┆     │
│ ont ┆ ont ┆ ció ┆ as  ┆ 467 ┆     ┆     ┆ ntr ┆ 475 ┆ a   ┆ d   ┆     ┆ obe ┆     ┆ a   ┆     ┆ @jc ┆ as  ┆     ┆ ntr ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆ mej ┆ 2   ┆ 8   ┆     ┆ S.L ┆     ┆     ┆     ┆     ┆ 1   ┆ 1   ┆ ont ┆ y   ┆     ┆ ntr ┆ ont ┆ de  ┆     ┆     │
│ rat ┆ rat ┆ n:  ┆ de  ┆     ┆     ┆     ┆ ata ┆ 97  ┆ de  ┆     ┆     ┆ rto ┆     ┆ de  ┆     ┆ yl. ┆ de  ┆     ┆ ata ┆     ┆ ata ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ata ┆     ┆     ┆     ┆     ┆ or  ┆     ┆     ┆     ┆ .   ┆     ┆     ┆     ┆     ┆     ┆     ┆ rat ┆ Leó ┆     ┆ ata ┆ rat ┆ con ┆     ┆     │
│ aci ┆ aci ┆ A20 ┆ eje ┆     ┆     ┆     ┆ cio ┆     ┆ Med ┆     ┆     ┆ Cor ┆     ┆ Med ┆     ┆ es  ┆ eje ┆     ┆ cio ┆     ┆ cio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cio ┆     ┆     ┆     ┆     ┆ rel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ aci ┆ n   ┆     ┆ cio ┆ aci ┆ str ┆     ┆     │
│ ond ┆ ond ┆ 25/ ┆ cuc ┆     ┆     ┆     ┆ nde ┆     ┆ io  ┆     ┆     ┆ tej ┆     ┆ io  ┆     ┆     ┆ cuc ┆     ┆ nde ┆     ┆ nde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nde ┆     ┆     ┆     ┆     ┆ aci ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ond ┆     ┆     ┆ nde ┆ ond ┆ ucc ┆     ┆     │
│ ele ┆ ele ┆ 010 ┆ ión ┆     ┆     ┆     ┆ les ┆     ┆ Amb ┆     ┆     ┆ oso ┆     ┆ Amb ┆     ┆     ┆ ión ┆     ┆ les ┆     ┆ les ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ les ┆     ┆     ┆     ┆     ┆ ón  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ele ┆     ┆     ┆ les ┆ ele ┆ ión ┆     ┆     │
│ sta ┆ sta ┆ 467 ┆ de  ┆     ┆     ┆     ┆ tad ┆     ┆ ien ┆     ┆     ┆ ,   ┆     ┆ ien ┆     ┆     ┆ de  ┆     ┆ tad ┆     ┆ tad ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tad ┆     ┆     ┆     ┆     ┆ cal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sta ┆     ┆     ┆ tad ┆ sta ┆ de  ┆     ┆     │
│ do. ┆ do. ┆ ;   ┆ aco ┆     ┆     ┆     ┆ o.e ┆     ┆ te, ┆     ┆     ┆ 14  ┆     ┆ te, ┆     ┆     ┆ aco ┆     ┆ o.e ┆     ┆ o.e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o.e ┆     ┆     ┆     ┆     ┆ ida ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ do. ┆     ┆     ┆ o.e ┆ do. ┆ inm ┆     ┆     │
│ es/ ┆ es/ ┆ Órg ┆ ndi ┆     ┆     ┆     ┆ s/c ┆     ┆ Viv ┆     ┆     ┆     ┆     ┆ Viv ┆     ┆     ┆ ndi ┆     ┆ s/c ┆     ┆ s/c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s/c ┆     ┆     ┆     ┆     ┆ d-p ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆ s/c ┆ es/ ┆ ueb ┆     ┆     │
│ sin ┆ wps ┆ ano ┆ cio ┆     ┆     ┆     ┆ odi ┆     ┆ ien ┆     ┆     ┆     ┆     ┆ ien ┆     ┆     ┆ cio ┆     ┆ odi ┆     ┆ odi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ odi ┆     ┆     ┆     ┆     ┆ rec ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Fil ┆     ┆     ┆ odi ┆ Fil ┆ les ┆     ┆     │
│ dic ┆ /po ┆ de  ┆ nam ┆     ┆     ┆     ┆ ce/ ┆     ┆ da  ┆     ┆     ┆     ┆     ┆ da  ┆     ┆     ┆ nam ┆     ┆ ce/ ┆     ┆ ce/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ce/ ┆     ┆     ┆     ┆     ┆ io. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eSy ┆     ┆     ┆ ce/ ┆ eSy ┆ de  ┆     ┆     │
│ aci ┆ c?u ┆ Con ┆ ien ┆     ┆     ┆     ┆ cl/ ┆     ┆ y   ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆ ien ┆     ┆ cl/ ┆     ┆ cl/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cl/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ste ┆     ┆     ┆ cl/ ┆ ste ┆ viv ┆     ┆     │
│ on/ ┆ ri= ┆ tra ┆ to  ┆     ┆     ┆     ┆ 2.1 ┆     ┆ Ord ┆     ┆     ┆     ┆     ┆ Ord ┆     ┆     ┆ to  ┆     ┆ 2.0 ┆     ┆ 1.0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2.0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m/s ┆     ┆     ┆ 2.0 ┆ m/s ┆ ien ┆     ┆     │
│ lic ┆ dee ┆ tac ┆ de  ┆     ┆     ┆     ┆ 0/C ┆     ┆ ena ┆     ┆     ┆     ┆     ┆ ena ┆     ┆     ┆ de  ┆     ┆ 8/C ┆     ┆ 4/W ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9/T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ erv ┆     ┆     ┆ 8/F ┆ erv ┆ das ┆     ┆     │
│ ita ┆ pli ┆ ión ┆ viv ┆     ┆     ┆     ┆ ont ┆     ┆ ció ┆     ┆     ┆     ┆     ┆ ció ┆     ┆     ┆ viv ┆     ┆ ont ┆     ┆ ork ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ end ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ let ┆     ┆     ┆ und ┆ let ┆ col ┆     ┆     │
│ cio ┆ nk: ┆ :   ┆ ien ┆     ┆     ┆     ┆ rac ┆     ┆ n   ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆ ien ┆     ┆ rac ┆     ┆ sCo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ erR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /Ge ┆     ┆     ┆ ing ┆ /Ge ┆ ect ┆     ┆     │
│ nes ┆ det ┆ Con ┆ da  ┆     ┆     ┆     ┆ tin ┆     ┆ del ┆     ┆     ┆     ┆     ┆ del ┆     ┆     ┆ da  ┆     ┆ tCo ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ esu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tDo ┆     ┆     ┆ Pro ┆ tDo ┆ iva ┆     ┆     │
│ Per ┆ all ┆ sej ┆ c/  ┆     ┆     ┆     ┆ gAu ┆     ┆ Ter ┆     ┆     ┆     ┆     ┆ Ter ┆     ┆     ┆ c/  ┆     ┆ de- ┆     ┆ act ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ltC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cum ┆     ┆     ┆ gra ┆ cum ┆ s y ┆     ┆     │
│ fil ┆ e_l ┆ erí ┆ El  ┆     ┆     ┆     ┆ tho ┆     ┆ rit ┆     ┆     ┆     ┆     ┆ rit ┆     ┆     ┆ El  ┆     ┆ 2.0 ┆     ┆ Cod ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ode ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ent ┆     ┆     ┆ mCo ┆ ent ┆ uni ┆     ┆     │
│ Con ┆ ici ┆ a   ┆ Pla ┆     ┆     ┆     ┆ rit ┆     ┆ ori ┆     ┆     ┆     ┆     ┆ ori ┆     ┆     ┆ Pla ┆     ┆ 8.g ┆     ┆ e-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -2. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ByI ┆     ┆     ┆ de- ┆ ByI ┆ fam ┆     ┆     │
│ tra ┆ tac ┆ de  ┆ ntí ┆     ┆     ┆     ┆ yCo ┆     ┆ o   ┆     ┆     ┆     ┆     ┆ o   ┆     ┆     ┆ ntí ┆     ┆ c   ┆     ┆ .04 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 09. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dSe ┆     ┆     ┆ 2.0 ┆ dSe ┆ ili ┆     ┆     │
│ tan ┆ ion ┆ Med ┆ o   ┆     ┆     ┆     ┆ de- ┆     ┆ de  ┆     ┆     ┆     ┆     ┆ de  ┆     ┆     ┆ o   ┆     ┆     ┆     ┆ .gc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gc  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rvl ┆     ┆     ┆ 8.g ┆ rvl ┆ are ┆     ┆     │
│ te/ ┆ &id ┆ io  ┆ nº  ┆     ┆     ┆     ┆ 2.1 ┆     ┆ la  ┆     ┆     ┆     ┆     ┆ la  ┆     ┆     ┆ nº  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ et? ┆     ┆     ┆ c   ┆ et? ┆ s   ┆     ┆     │
│ 176 ┆ Evl ┆ Amb ┆ 6,  ┆     ┆     ┆     ┆ 0.g ┆     ┆ Jun ┆     ┆     ┆     ┆     ┆ Jun ┆     ┆     ┆ 6,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Doc ┆     ┆     ┆     ┆ Doc ┆     ┆     ┆     │
│ 806 ┆ =wj ┆ ien ┆ 2º  ┆     ┆     ┆     ┆ c   ┆     ┆ ta  ┆     ┆     ┆     ┆     ┆ ta  ┆     ┆     ┆ 2º  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ume ┆     ┆     ┆     ┆ ume ┆     ┆     ┆     │
│ 02  ┆ nyT ┆ te, ┆ B,  ┆     ┆     ┆     ┆     ┆     ┆ de  ┆     ┆     ┆     ┆     ┆ de  ┆     ┆     ┆ B,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ntI ┆     ┆     ┆     ┆ ntI ┆     ┆     ┆     │
│     ┆ FxH ┆ Viv ┆ Ped ┆     ┆     ┆     ┆     ┆     ┆ Cas ┆     ┆     ┆     ┆     ┆ Cas ┆     ┆     ┆ Ped ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dPa ┆     ┆     ┆     ┆ dPa ┆     ┆     ┆     │
│     ┆ 69m ┆ ien ┆ raj ┆     ┆     ┆     ┆     ┆     ┆ til ┆     ┆     ┆     ┆     ┆ til ┆     ┆     ┆ raj ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ram ┆     ┆     ┆     ┆ ram ┆     ┆     ┆     │
│     ┆ KeV ┆ da  ┆ as  ┆     ┆     ┆     ┆     ┆     ┆ la  ┆     ┆     ┆     ┆     ┆ la  ┆     ┆     ┆ as  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ =nr ┆     ┆     ┆     ┆ =9I ┆     ┆     ┆     │
│     ┆ WTb ┆ y   ┆ de  ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆ de  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ KNp ┆     ┆     ┆     ┆ zzh ┆     ┆     ┆     │
│     ┆ 9Sc ┆ Ord ┆ San ┆     ┆     ┆     ┆     ┆     ┆ Leó ┆     ┆     ┆     ┆     ┆ Leó ┆     ┆     ┆ San ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ aet ┆     ┆     ┆     ┆ W1B ┆     ┆     ┆     │
│     ┆ o…  ┆ ena ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ k…  ┆     ┆     ┆     ┆ o…  ┆     ┆     ┆     │
│     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ htt ┆ htt ┆ Id  ┆ Obr ┆ A20 ┆ RES ┆ 2   ┆ htt ┆ 210 ┆ Con ┆ Val ┆ 470 ┆ Cal ┆ ES  ┆ Con ┆ nul ┆ sco ┆ Obr ┆ 3   ┆ htt ┆ 453 ┆ htt ┆ 152 ┆ 167 ┆ 152 ┆ 452 ┆ ES4 ┆ 540 ┆ DAY ┆ nul ┆ 8   ┆ htt ┆ nul ┆ nul ┆ nul ┆ nul ┆ Ofe ┆ 202 ┆ 202 ┆ B09 ┆ CHR ┆ 146 ┆ 161 ┆ 5   ┆ htt ┆ 202 ┆ 202 ┆ htt ┆ nul ┆ REU ┆ htt ┆ htt ┆ Tra ┆ nul ┆ 202 │
│ ps: ┆ ps: ┆ lic ┆ as  ┆ 22/ ┆     ┆     ┆ p:/ ┆ 383 ┆ sej ┆ lad ┆ 14  ┆ le  ┆     ┆ sej ┆ l   ┆ ad. ┆ as  ┆     ┆ p:/ ┆ 4   ┆ p:/ ┆ 487 ┆ 736 ┆ 487 ┆ 111 ┆ 16  ┆     ┆     ┆ l   ┆     ┆ p:/ ┆ l   ┆ l   ┆ l   ┆ l   ┆ rta ┆ 2-0 ┆ 2-0 ┆ 266 ┆ EUR ┆ 662 ┆ 329 ┆     ┆ p:/ ┆ 2-0 ┆ 2-0 ┆ ps: ┆ l   ┆     ┆ p:/ ┆ ps: ┆ baj ┆ l   ┆ 2   │
│ //c ┆ //c ┆ ita ┆ de  ┆ 000 ┆     ┆     ┆ /co ┆ 701 ┆ erí ┆ oli ┆     ┆ Rig ┆     ┆ erí ┆     ┆ fym ┆ de  ┆     ┆ /co ┆     ┆ /co ┆ 9.5 ┆ 7.5 ┆ 9.5 ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆ /co ┆     ┆     ┆     ┆     ┆ con ┆ 5-1 ┆ 6-0 ┆ 420 ┆ OPA ┆ 9.1 ┆ 2.0 ┆     ┆ /co ┆ 1-1 ┆ 1-1 ┆ //c ┆     ┆     ┆ /co ┆ //c ┆ os  ┆     ┆     │
│ ont ┆ ont ┆ ció ┆ ref ┆ 190 ┆     ┆     ┆ ntr ┆ 475 ┆ a   ┆ d   ┆     ┆ obe ┆     ┆ a   ┆     ┆ a@j ┆ ref ┆     ┆ ntr ┆     ┆ ntr ┆ 7   ┆ 3   ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆ mej ┆ 2   ┆ 7   ┆     ┆ GES ┆ 7   ┆ 9   ┆     ┆ ntr ┆ 7   ┆ 7   ┆ ont ┆     ┆     ┆ ntr ┆ ont ┆ de  ┆     ┆     │
│ rat ┆ rat ┆ n:  ┆ orm ┆     ┆     ┆     ┆ ata ┆ 97  ┆ de  ┆     ┆     ┆ rto ┆     ┆ de  ┆     ┆ cyl ┆ orm ┆     ┆ ata ┆     ┆ ata ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ata ┆     ┆     ┆     ┆     ┆ or  ┆     ┆     ┆     ┆ TIO ┆     ┆     ┆     ┆ ata ┆     ┆     ┆ rat ┆     ┆     ┆ ata ┆ rat ┆ con ┆     ┆     │
│ aci ┆ aci ┆ A20 ┆ a y ┆     ┆     ┆     ┆ cio ┆     ┆ Med ┆     ┆     ┆ Cor ┆     ┆ Med ┆     ┆ .es ┆ a y ┆     ┆ cio ┆     ┆ cio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cio ┆     ┆     ┆     ┆     ┆ rel ┆     ┆     ┆     ┆ N Y ┆     ┆     ┆     ┆ cio ┆     ┆     ┆ aci ┆     ┆     ┆ cio ┆ aci ┆ str ┆     ┆     │
│ ond ┆ ond ┆ 22/ ┆ mej ┆     ┆     ┆     ┆ nde ┆     ┆ io  ┆     ┆     ┆ tej ┆     ┆ io  ┆     ┆     ┆ mej ┆     ┆ nde ┆     ┆ nde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nde ┆     ┆     ┆     ┆     ┆ aci ┆     ┆     ┆     ┆ CON ┆     ┆     ┆     ┆ nde ┆     ┆     ┆ ond ┆     ┆     ┆ nde ┆ ond ┆ ucc ┆     ┆     │
│ ele ┆ ele ┆ 000 ┆ ora ┆     ┆     ┆     ┆ les ┆     ┆ Amb ┆     ┆     ┆ oso ┆     ┆ Amb ┆     ┆     ┆ ora ┆     ┆ les ┆     ┆ les ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ les ┆     ┆     ┆     ┆     ┆ ón  ┆     ┆     ┆     ┆ STR ┆     ┆     ┆     ┆ les ┆     ┆     ┆ ele ┆     ┆     ┆ les ┆ ele ┆ ión ┆     ┆     │
│ sta ┆ sta ┆ 190 ┆ de  ┆     ┆     ┆     ┆ tad ┆     ┆ ien ┆     ┆     ┆ ,   ┆     ┆ ien ┆     ┆     ┆ de  ┆     ┆ tad ┆     ┆ tad ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tad ┆     ┆     ┆     ┆     ┆ cal ┆     ┆     ┆     ┆ UCC ┆     ┆     ┆     ┆ tad ┆     ┆     ┆ sta ┆     ┆     ┆ tad ┆ sta ┆ par ┆     ┆     │

In [24]:
null_count = v["n_viviendas"].null_count()
print(f"Total de nulos: {null_count}")

Total de nulos: 518

In [25]:
no_estado = v.filter(
    (pl.col("ContractingPartyTypeCode") != "1")
)
len(no_estado)

1048

In [26]:
estado = v.filter(
    (pl.col("ContractingPartyTypeCode") == "1")
)

estado

shape: (26, 54)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ id  ┆ lin ┆ sum ┆ tit ┆ Con ┆ Con ┆ Con ┆ Con ┆ ID  ┆ Nam ┆ Cit ┆ Pos ┆ Lin ┆ Ide ┆ Nam ┆ Tel ┆ Ele ┆ Nam ┆ Typ ┆ Typ ┆ Sub ┆ Sub ┆ Est ┆ Tot ┆ Tax ┆ Ite ┆ Cou ┆ Dur ┆ Dur ┆ Opt ┆ Res ┆ Res ┆ Nam ┆ Tot ┆ Tax ┆ Ite ┆ Des ┆ Awa ┆ Iss ┆ ID_ ┆ Nam ┆ Tax ┆ Pay ┆ Eva ┆ Eva ┆ End ┆ End ┆ URI ┆ Nam ┆ Fun ┆ Fun ┆ URI ┆ ES  ┆ n_v │
│ --- ┆ k_h ┆ mar ┆ le  ┆ tra ┆ tra ┆ tra ┆ tra ┆ --- ┆ e   ┆ yNa ┆ tal ┆ e   ┆ nti ┆ e_2 ┆ eph ┆ ctr ┆ e_3 ┆ eCo ┆ eCo ┆ Typ ┆ Typ ┆ ima ┆ alA ┆ Exc ┆ mCl ┆ ntr ┆ ati ┆ ati ┆ ion ┆ ult ┆ ult ┆ e_4 ┆ alA ┆ Exc ┆ mCl ┆ cri ┆ rdD ┆ ueD ┆ 2   ┆ e_5 ┆ Exc ┆ abl ┆ lua ┆ lua ┆ Dat ┆ Dat ┆ _1  ┆ e_6 ┆ din ┆ din ┆ _4  ┆ --- ┆ ivi │
│ str ┆ ref ┆ y   ┆ --- ┆ ctF ┆ ctF ┆ cti ┆ cti ┆ str ┆ --- ┆ me  ┆ Zon ┆ --- ┆ fic ┆ --- ┆ one ┆ oni ┆ --- ┆ de  ┆ de_ ┆ eCo ┆ eCo ┆ ted ┆ mou ┆ lus ┆ ass ┆ ySu ┆ onM ┆ onM ┆ sDe ┆ Cod ┆ Cod ┆ --- ┆ mou ┆ lus ┆ ass ┆ pti ┆ ate ┆ ate ┆ --- ┆ --- ┆ lus ┆ eAm ┆ tio ┆ tio ┆ e   ┆ e_1 ┆ --- ┆ --- ┆ gPr ┆ gPr ┆ --- ┆ str ┆ end │
│     ┆ --- ┆ --- ┆ str ┆ old ┆ old ┆ ngP ┆ ngP ┆     ┆ str ┆ --- ┆ e   ┆ str ┆ ati ┆ str ┆ --- ┆ cMa ┆ str ┆ --- ┆ lis ┆ de  ┆ de_ ┆ Ove ┆ nt  ┆ ive ┆ ifi ┆ ben ┆ eas ┆ eas ┆ scr ┆ e   ┆ e_l ┆ str ┆ nt_ ┆ ive ┆ ifi ┆ on  ┆ --- ┆ --- ┆ str ┆ str ┆ ive ┆ oun ┆ nCr ┆ nCr ┆ --- ┆ --- ┆ str ┆ str ┆ ogr ┆ ogr ┆ str ┆     ┆ as  │
│     ┆ str ┆ str ┆     ┆ erI ┆ erS ┆ art ┆ art ┆     ┆     ┆ str ┆ --- ┆     ┆ onC ┆     ┆ str ┆ il  ┆     ┆ str ┆ tUR ┆ --- ┆ lis ┆ ral ┆ --- ┆ Amo ┆ cat ┆ tit ┆ ure ┆ ure ┆ ipt ┆ --- ┆ ist ┆     ┆ 1   ┆ Amo ┆ cat ┆ --- ┆ str ┆ str ┆     ┆     ┆ Amo ┆ t   ┆ ite ┆ ite ┆ str ┆ str ┆     ┆     ┆ amC ┆ amC ┆     ┆     ┆ --- │
│     ┆     ┆     ┆     ┆ D   ┆ tat ┆ yTy ┆ yTy ┆     ┆     ┆     ┆ str ┆     ┆ ode ┆     ┆     ┆ --- ┆     ┆     ┆ I   ┆ str ┆ tUR ┆ lCo ┆ str ┆ unt ┆ ion ┆ yCo ┆ --- ┆ _un ┆ ion ┆ str ┆ URI ┆     ┆ --- ┆ unt ┆ ion ┆ str ┆     ┆     ┆     ┆     ┆ unt ┆ --- ┆ ria ┆ ria ┆     ┆     ┆     ┆     ┆ ode ┆ ode ┆     ┆     ┆ i32 │
│     ┆     ┆     ┆     ┆ --- ┆ usC ┆ peC ┆ peC ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆ I   ┆ ntr ┆     ┆ --- ┆ Cod ┆ de  ┆ i32 ┆ itC ┆ --- ┆     ┆ --- ┆     ┆ str ┆ _1  ┆ Cod ┆     ┆     ┆     ┆     ┆     ┆ _2  ┆ str ┆ Typ ┆ Typ ┆     ┆     ┆     ┆     ┆ --- ┆ _li ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆ ode ┆ ode ┆ ode ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ act ┆     ┆ str ┆ e   ┆ --- ┆     ┆ ode ┆ str ┆     ┆ str ┆     ┆     ┆ --- ┆ e_1 ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ eCo ┆ eCo ┆     ┆     ┆     ┆     ┆ str ┆ stU ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ _li ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ Amo ┆     ┆     ┆ --- ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ de_ ┆ de_ ┆     ┆     ┆     ┆     ┆     ┆ RI  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ stU ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ unt ┆     ┆     ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ lis ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RI  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ tUR ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ I_1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ htt ┆ htt ┆ Id  ┆ Obr ┆ 202 ┆ RES ┆ 1   ┆ htt ┆ 100 ┆ Int ┆ San ┆ 111 ┆ Ars ┆ ES  ┆ Int ┆ 956 ┆ juc ┆ Obr ┆ 3   ┆ htt ┆ 454 ┆ htt ┆ 196 ┆ 237 ┆ 196 ┆ 452 ┆ ES6 ┆ 120 ┆ DAY ┆ nul ┆ 3   ┆ htt ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 202 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 5   ┆ htt ┆ nul ┆ 202 ┆ htt ┆ Int ┆ NO- ┆ htt ┆ htt ┆ Tra ┆ nul │
│ ps: ┆ ps: ┆ lic ┆ as  ┆ 5/A ┆     ┆     ┆ p:/ ┆ 001 ┆ end ┆ Fer ┆ 10  ┆ ena ┆     ┆ end ┆ 599 ┆ odi ┆ as  ┆     ┆ p:/ ┆ 5   ┆ p:/ ┆ 049 ┆ 220 ┆ 049 ┆ 110 ┆ 12  ┆     ┆     ┆ l   ┆     ┆ p:/ ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 5-0 ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆ p:/ ┆ l   ┆ 5-0 ┆ ps: ┆ end ┆ EU  ┆ p:/ ┆ ps: ┆ baj ┆ l   │
│ //c ┆ //c ┆ ita ┆ var ┆ R43 ┆     ┆     ┆ /co ┆ 400 ┆ ent ┆ nan ┆     ┆ l   ┆     ┆ ent ┆ 245 ┆ z@f ┆ var ┆     ┆ /co ┆     ┆ /co ┆ .78 ┆ .23 ┆ .78 ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆ /co ┆     ┆     ┆     ┆     ┆     ┆ 5-2 ┆     ┆     ┆     ┆     ┆     ┆     ┆ /co ┆     ┆ 5-1 ┆ //c ┆ enc ┆     ┆ /co ┆ //c ┆ os  ┆     │
│ ont ┆ ont ┆ ció ┆ ias ┆ U/0 ┆     ┆     ┆ ntr ┆ 005 ┆ e   ┆ do  ┆     ┆ de  ┆     ┆ e   ┆     ┆ n.m ┆ ias ┆     ┆ ntr ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆ 9   ┆ ont ┆ ia  ┆     ┆ ntr ┆ ont ┆ de  ┆     │
│ rat ┆ rat ┆ n:  ┆ de  ┆ 000 ┆     ┆     ┆ ata ┆ 84  ┆ de  ┆     ┆     ┆ Cád ┆     ┆ de  ┆     ┆ de. ┆ de  ┆     ┆ ata ┆     ┆ ata ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ata ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ata ┆     ┆     ┆ rat ┆ de  ┆     ┆ ata ┆ rat ┆ con ┆     │
│ aci ┆ aci ┆ 202 ┆ ref ┆ 046 ┆     ┆     ┆ cio ┆     ┆ San ┆     ┆     ┆ iz- ┆     ┆ San ┆     ┆ es  ┆ ref ┆     ┆ cio ┆     ┆ cio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cio ┆     ┆     ┆ aci ┆ San ┆     ┆ cio ┆ aci ┆ str ┆     │
│ ond ┆ ond ┆ 5/A ┆ orm ┆ 4*  ┆     ┆     ┆ nde ┆     ┆ Fer ┆     ┆     ┆ Bas ┆     ┆ Fer ┆     ┆     ┆ orm ┆     ┆ nde ┆     ┆ nde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nde ┆     ┆     ┆ ond ┆ Fer ┆     ┆ nde ┆ ond ┆ ucc ┆     │
│ ele ┆ ele ┆ R43 ┆ a   ┆     ┆     ┆     ┆ les ┆     ┆ nan ┆     ┆     ┆ e   ┆     ┆ nan ┆     ┆     ┆ a   ┆     ┆ les ┆     ┆ les ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ les ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ les ┆     ┆     ┆ ele ┆ nan ┆     ┆ les ┆ ele ┆ ión ┆     │
│ sta ┆ sta ┆ U/0 ┆ en  ┆     ┆     ┆     ┆ tad ┆     ┆ do  ┆     ┆     ┆ Nav ┆     ┆ do  ┆     ┆     ┆ en  ┆     ┆ tad ┆     ┆ tad ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tad ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tad ┆     ┆     ┆ sta ┆ do  ┆     ┆ tad ┆ sta ┆ de  ┆     │
│ do. ┆ do. ┆ 000 ┆ el  ┆     ┆     ┆     ┆ o.e ┆     ┆     ┆     ┆     ┆ al  ┆     ┆     ┆     ┆     ┆ el  ┆     ┆ o.e ┆     ┆ o.e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o.e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o.e ┆     ┆     ┆ do. ┆     ┆     ┆ o.e ┆ do. ┆ inm ┆     │
│ es/ ┆ es/ ┆ 046 ┆ Pal ┆     ┆     ┆     ┆ s/c ┆     ┆     ┆     ┆     ┆ de  ┆     ┆     ┆     ┆     ┆ Pal ┆     ┆ s/c ┆     ┆ s/c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s/c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s/c ┆     ┆     ┆ es/ ┆     ┆     ┆ s/c ┆ es/ ┆ ueb ┆     │
│ sin ┆ wps ┆ 4*; ┆ aci ┆     ┆     ┆     ┆ odi ┆     ┆     ┆     ┆     ┆ la  ┆     ┆     ┆     ┆     ┆ aci ┆     ┆ odi ┆     ┆ odi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ odi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ odi ┆     ┆     ┆ Fil ┆     ┆     ┆ odi ┆ Fil ┆ les ┆     │
│ dic ┆ /po ┆ Órg ┆ o   ┆     ┆     ┆     ┆ ce/ ┆     ┆     ┆     ┆     ┆ Car ┆     ┆     ┆     ┆     ┆ o   ┆     ┆ ce/ ┆     ┆ ce/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ce/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ce/ ┆     ┆     ┆ eSy ┆     ┆     ┆ ce/ ┆ eSy ┆ de  ┆     │
│ aci ┆ c?u ┆ ano ┆ de  ┆     ┆     ┆     ┆ cl/ ┆     ┆     ┆     ┆     ┆ rac ┆     ┆     ┆     ┆     ┆ de  ┆     ┆ cl/ ┆     ┆ cl/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cl/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cl/ ┆     ┆     ┆ ste ┆     ┆     ┆ cl/ ┆ ste ┆ viv ┆     │
│ on/ ┆ ri= ┆ de  ┆ la  ┆     ┆     ┆     ┆ 2.1 ┆     ┆     ┆     ┆     ┆ a.  ┆     ┆     ┆     ┆     ┆ la  ┆     ┆ 2.0 ┆     ┆ 1.0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2.0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2.0 ┆     ┆     ┆ m/s ┆     ┆     ┆ 2.0 ┆ m/s ┆ ien ┆     │
│ lic ┆ dee ┆ Con ┆ Cap ┆     ┆     ┆     ┆ 0/C ┆     ┆     ┆     ┆     ┆ Sec ┆     ┆     ┆     ┆     ┆ Cap ┆     ┆ 8/C ┆     ┆ 4/W ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9/T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /Fi ┆     ┆     ┆ erv ┆     ┆     ┆ 8/F ┆ erv ┆ das ┆     │
│ ita ┆ pli ┆ tra ┆ ita ┆     ┆     ┆     ┆ ont ┆     ┆     ┆     ┆     ┆ ció ┆     ┆     ┆     ┆     ┆ ita ┆     ┆ ont ┆     ┆ ork ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ end ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nan ┆     ┆     ┆ let ┆     ┆     ┆ und ┆ let ┆ col ┆     │
│ cio ┆ nk: ┆ tac ┆ nía ┆     ┆     ┆     ┆ rac ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆ nía ┆     ┆ rac ┆     ┆ sCo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ erR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cia ┆     ┆     ┆ /Ge ┆     ┆     ┆ ing ┆ /Ge ┆ ect ┆     │
│ nes ┆ det ┆ ión ┆ Gen ┆     ┆     ┆     ┆ tin ┆     ┆     ┆     ┆     ┆ de  ┆     ┆     ┆     ┆     ┆ Gen ┆     ┆ tCo ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ esu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lCa ┆     ┆     ┆ tDo ┆     ┆     ┆ Pro ┆ tDo ┆ iva ┆     │
│ Per ┆ all ┆ :   ┆ era ┆     ┆     ┆     ┆ gAu ┆     ┆     ┆     ┆     ┆ Con ┆     ┆     ┆     ┆     ┆ era ┆     ┆ de- ┆     ┆ act ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ltC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pab ┆     ┆     ┆ cum ┆     ┆     ┆ gra ┆ cum ┆ s y ┆     │
│ fil ┆ e_l ┆ Int ┆ l   ┆     ┆     ┆     ┆ tho ┆     ┆     ┆     ┆     ┆ tra ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ 2.0 ┆     ┆ Cod ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ode ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ili ┆     ┆     ┆ ent ┆     ┆     ┆ mCo ┆ ent ┆ uni ┆     │
│ Con ┆ ici ┆ end ┆     ┆     ┆     ┆     ┆ rit ┆     ┆     ┆     ┆     ┆ tac ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8.g ┆     ┆ e-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -2. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tyT ┆     ┆     ┆ ByI ┆     ┆     ┆ de- ┆ ByI ┆ fam ┆     │
│ tra ┆ tac ┆ ent ┆     ┆     ┆     ┆     ┆ yCo ┆     ┆     ┆     ┆     ┆ ión ┆     ┆     ┆     ┆     ┆     ┆     ┆ c   ┆     ┆ .04 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 09. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ype ┆     ┆     ┆ dSe ┆     ┆     ┆ 2.0 ┆ dSe ┆ ili ┆     │
│ tan ┆ ion ┆ e   ┆     ┆     ┆     ┆     ┆ de- ┆     ┆     ┆     ┆     ┆ .   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .gc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gc  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Cod ┆     ┆     ┆ rvl ┆     ┆     ┆ 8.g ┆ rvl ┆ are ┆     │
│ te/ ┆ &id ┆ de  ┆     ┆     ┆     ┆     ┆ 2.1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e-2 ┆     ┆     ┆ et? ┆     ┆     ┆ c   ┆ et? ┆ s   ┆     │
│ 171 ┆ Evl ┆ San ┆     ┆     ┆     ┆     ┆ 0.g ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0. ┆     ┆     ┆ Doc ┆     ┆     ┆     ┆ Doc ┆     ┆     │
│ 945 ┆ =9v ┆ Fer ┆     ┆     ┆     ┆     ┆ c   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gc  ┆     ┆     ┆ ume ┆     ┆     ┆     ┆ ume ┆     ┆     │
│ 98  ┆ qV9 ┆ nan ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ntI ┆     ┆     ┆     ┆ ntI ┆     ┆     │
│     ┆ cPS ┆ do; ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dPa ┆     ┆     ┆     ┆ dPa ┆     ┆     │
│     ┆ ftC ┆ Imp ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ram ┆     ┆     ┆     ┆ ram ┆     ┆     │
│     ┆ AAM ┆ ort ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ =PV ┆     ┆     ┆     ┆ =v8 ┆     ┆     │
│     ┆ 7L0 ┆ e:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4Ea ┆     ┆     ┆     ┆ Gns ┆     ┆     │
│     ┆ 3kM ┆ 19… ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p%2 ┆     ┆     ┆     ┆ V2C ┆     ┆     │
│     ┆ 8…  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ B…  ┆     ┆     ┆     ┆ M…  ┆     ┆     │
│ htt ┆ htt ┆ Id  ┆ EXP ┆ 202 ┆ RES ┆ 1   ┆ htt ┆ 100 ┆ Int ┆ Fer ┆ 154 ┆ ARS ┆ ES  ┆ Int ┆ 981 ┆ a3j ┆ EXP ┆ 3   ┆ htt ┆ 451 ┆ htt ┆ 109 ┆ 132 ┆ 109 ┆ 452 ┆ ES1 ┆ 60  ┆ DAY ┆ nul ┆ 9   ┆ htt ┆ nul ┆ nul ┆ nul ┆ nul ┆ La  ┆ 202 ┆ 202 ┆ B94 ┆ CyS ┆ 960 ┆ 116 ┆ nul ┆ nul ┆ 202 ┆ 202 ┆ htt ┆ Int ┆ NO- ┆ htt ┆ htt ┆ Tra ┆ nul │
│ ps: ┆ ps: ┆ lic ┆ EDI ┆ 5/A ┆     ┆     ┆ p:/ ┆ 001 ┆ end ┆ rol ┆ 90  ┆ ENA ┆     ┆ end ┆ 336 ┆ uco ┆ EDI ┆     ┆ p:/ ┆ 0   ┆ p:/ ┆ 670 ┆ 701 ┆ 670 ┆ 111 ┆     ┆     ┆     ┆ l   ┆     ┆ p:/ ┆ l   ┆ l   ┆ l   ┆ l   ┆ Mes ┆ 5-1 ┆ 5-1 ┆ 039 ┆ San ┆ 00  ┆ 160 ┆ l   ┆ l   ┆ 5-0 ┆ 5-0 ┆ ps: ┆ end ┆ EU  ┆ p:/ ┆ ps: ┆ baj ┆ l   │
│ //c ┆ //c ┆ ita ┆ ENT ┆ R42 ┆     ┆     ┆ /co ┆ 400 ┆ ent ┆ (A  ┆     ┆ L   ┆     ┆ ent ┆ 207 ┆ fer ┆ ENT ┆     ┆ /co ┆     ┆ /co ┆ .46 ┆ .26 ┆ .46 ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆ /co ┆     ┆     ┆     ┆     ┆ a   ┆ 0-1 ┆ 0-2 ┆ 203 ┆ BLA ┆     ┆     ┆     ┆     ┆ 9-1 ┆ 9-1 ┆ //c ┆ enc ┆     ┆ /co ┆ //c ┆ os  ┆     │
│ ont ┆ ont ┆ ció ┆ E   ┆ U/0 ┆     ┆     ┆ ntr ┆ 063 ┆ e   ┆ Cor ┆     ┆ MIL ┆     ┆ e   ┆     ┆ @fn ┆ E   ┆     ┆ ntr ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆ del ┆ 3   ┆ 1   ┆     ┆ S,s ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆ ont ┆ ia  ┆     ┆ ntr ┆ ont ┆ de  ┆     │
│ rat ┆ rat ┆ n:  ┆ INV ┆ 000 ┆     ┆     ┆ ata ┆ 81  ┆ de  ┆ uña ┆     ┆ ITA ┆     ┆ de  ┆     ┆ .md ┆ INV ┆     ┆ ata ┆     ┆ ata ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ata ┆     ┆     ┆     ┆     ┆ Órg ┆     ┆     ┆     ┆ .l. ┆     ┆     ┆     ┆     ┆     ┆     ┆ rat ┆ de  ┆     ┆ ata ┆ rat ┆ con ┆     │
│ aci ┆ aci ┆ 202 ┆ IED ┆ 210 ┆     ┆     ┆ cio ┆     ┆ Fer ┆ )   ┆     ┆ R   ┆     ┆ Fer ┆     ┆ e.e ┆ IED ┆     ┆ cio ┆     ┆ cio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cio ┆     ┆     ┆     ┆     ┆ ano ┆     ┆     ┆     ┆ u.  ┆     ┆     ┆     ┆     ┆     ┆     ┆ aci ┆ El  ┆     ┆ cio ┆ aci ┆ str ┆     │
│ ond ┆ ond ┆ 5/A ┆ NUM ┆ 9E  ┆     ┆     ┆ nde ┆     ┆ rol ┆     ┆     ┆ CAL ┆     ┆ rol ┆     ┆ s   ┆ NUM ┆     ┆ nde ┆     ┆ nde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nde ┆     ┆     ┆     ┆     ┆ Con ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ond ┆ Fer ┆     ┆ nde ┆ ond ┆ ucc ┆     │
│ ele ┆ ele ┆ R42 ┆ .   ┆     ┆     ┆     ┆ les ┆     ┆     ┆     ┆     ┆ LE  ┆     ┆     ┆     ┆     ┆ .   ┆     ┆ les ┆     ┆ les ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ les ┆     ┆     ┆     ┆     ┆ tra ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ele ┆ rol ┆     ┆ les ┆ ele ┆ ión ┆     │
│ sta ┆ sta ┆ U/0 ┆ 202 ┆     ┆     ┆     ┆ tad ┆     ┆     ┆     ┆     ┆ IRM ┆     ┆     ┆     ┆     ┆ 202 ┆     ┆ tad ┆     ┆ tad ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tad ┆     ┆     ┆     ┆     ┆ tac ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sta ┆     ┆     ┆ tad ┆ sta ┆ par ┆     │
│ do. ┆ do. ┆ 000 ┆ 500 ┆     ┆     ┆     ┆ o.e ┆     ┆     ┆     ┆     ┆ AND ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆ o.e ┆     ┆ o.e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o.e ┆     ┆     ┆     ┆     ┆ ión ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ do. ┆     ┆     ┆ o.e ┆ do. ┆ a   ┆     │
│ es/ ┆ es/ ┆ 210 ┆ 000 ┆     ┆     ┆     ┆ s/c ┆     ┆     ┆     ┆     ┆ IÑO ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆ s/c ┆     ┆ s/c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s/c ┆     ┆     ┆     ┆     ┆ pro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆ s/c ┆ es/ ┆ viv ┆     │

In [27]:
barcelona = c.filter(
    (pl.col("CityName") == "Barcelona")
)

In [28]:
len(barcelona)

0

In [29]:
heliopol = df_total.filter(
    (pl.col("ID_2") == "268931") 
)
heliopol

shape: (13, 273)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ id  ┆ lin ┆ sum ┆ sum ┆ tit ┆ upd ┆ Con ┆ Con ┆ Con ┆ Con ┆ Con ┆ Con ┆ Web ┆ ID  ┆ ID_ ┆ Nam ┆ Cit ┆ Pos ┆ Lin ┆ Ide ┆ Ide ┆ Nam ┆ Nam ┆ Tel ┆ Tel ┆ Ele ┆ Nam ┆ Typ ┆ Typ ┆ Sub ┆ Sub ┆ Est ┆ Est ┆ Tot ┆ Tot ┆ Tax ┆ Tax ┆ Ite ┆ Ite ┆ Cou ┆ Cou ┆ Cou ┆ Dur ┆ Dur ┆ Opt ┆ ID_ ┆ ID_ ┆ Nam ┆ Tot ┆ Tot ┆ Tax ┆ Tax ┆ Ite ┆ Ite ┆ Res ┆ Res ┆ Des ┆ Awa ┆ Iss ┆ ID_ ┆ ID_ ┆ Nam ┆ Pro ┆ Tax ┆ Tax ┆ Pay ┆ Pay ┆ Var ┆ Gua ┆ Gua ┆ Amo ┆ Des ┆ Eva ┆ Eva ┆ Eva ┆ Eva ┆ Req ┆ Req ┆ ID_ ┆ Pro ┆ Pro ┆ Urg ┆ Urg ┆ End ┆ End ┆ End ┆ ID_ ┆ URI ┆ Doc ┆ ID_ ┆ URI ┆ Doc ┆ ID_ ┆ URI ┆ Doc ┆ Not ┆ Not ┆ Pub ┆ Iss ┆ Nam ┆ Nam ┆ Nam ┆ Nam ┆ Nam ┆ Nam ┆ Ide ┆ Ide ┆ Nam ┆ End ┆ Des ┆ Rec ┆ Per ┆ Sta ┆ Sta ┆ End ┆ ID_ ┆ Con ┆ Con ┆ Des ┆ Rat ┆ Low ┆ Low ┆ Hig ┆ Hig ┆ Pri ┆ Des ┆ Des ┆ Cit ┆ ID_ ┆ Cod ┆ Pos ┆ Lia ┆ Lia ┆ ID_ ┆ Not ┆ Con ┆ Con ┆ Fin ┆ Fin ┆ Con ┆ Tax ┆ Tax ┆ Tax ┆ Tax ┆ Fun ┆ Fun ┆ Fun ┆ Min ┆ Des ┆ Lim ┆ Exp ┆ Max ┆ sou ┆ Req ┆ Des ┆ Wei ┆ Nam ┆ Act ┆ Act ┆ Buy ┆ ID_ ┆ ID_ ┆ ID_ ┆ ID_ ┆ Mix ┆ SME ┆ SME ┆ Cou ┆ Cou ┆ Cou ┆ Cit ┆ Pos ┆ Ide ┆ Ide ┆ Ide ┆ Fun ┆ Pro ┆ Pro ┆ ID_ ┆ Sub ┆ Sub ┆ Ove ┆ ID_ ┆ Doc ┆ Doc ┆ URI ┆ Fil ┆ Des ┆ Nam ┆ Exe ┆ Exe ┆ Des ┆ Awa ┆ Awa ┆ Awa ┆ Awa ┆ End ┆ Auc ┆ Rec ┆ Doc ┆ Doc ┆ Doc ┆ URI ┆ Fil ┆ UUI ┆ UUI ┆ Awa ┆ Awa ┆ Not ┆ Age ┆ Sen ┆ Sen ┆ Eva ┆ Eva ┆ Des ┆ Eva ┆ Eva ┆ Des ┆ Cou ┆ Cou ┆ Cou ┆ Ide ┆ Ide ┆ Nam ┆ Par ┆ Par ┆ Par ┆ Max ┆ Max ┆ Thr ┆ Thr ┆ Thr ┆ Thr ┆ Req ┆ Req ┆ Des ┆ Awa ┆ Awa ┆ Des ┆ Not ┆ Awa ┆ Awa ┆ Wei ┆ End ┆ End ┆ Str ┆ Abn ┆ Emp ┆ Emp ┆ Des ┆ ID_ ┆ ID_ ┆ EUN ┆ Non ┆ ID_ ┆ ID_ ┆ Str ┆ Cit ┆ Pos ┆ Lot ┆ Des ┆ ID_ ┆ ID_ ┆ Ope ┆ Ope ┆ Rat ┆ Nam ┆ Com ┆ Com ┆ ID_ ┆ ID_ ┆ ID_ ┆ Pro │
│ --- ┆ k_h ┆ mar ┆ mar ┆ le  ┆ ate ┆ tra ┆ tra ┆ tra ┆ tra ┆ tra ┆ tra ┆ sit ┆ --- ┆ sch ┆ e   ┆ yNa ┆ tal ┆ e   ┆ nti ┆ nti ┆ e_1 ┆ e_2 ┆ eph ┆ efa ┆ ctr ┆ e_3 ┆ eCo ┆ eCo ┆ Typ ┆ Typ ┆ ima ┆ ima ┆ alA ┆ alA ┆ Exc ┆ Exc ┆ mCl ┆ mCl ┆ ntr ┆ ntr ┆ ntr ┆ ati ┆ ati ┆ ion ┆ 1   ┆ sch ┆ e_4 ┆ alA ┆ alA ┆ Exc ┆ Exc ┆ mCl ┆ mCl ┆ ult ┆ ult ┆ cri ┆ rdD ┆ ueD ┆ 2   ┆ sch ┆ e_5 ┆ cur ┆ Exc ┆ Exc ┆ abl ┆ abl ┆ ian ┆ ran ┆ ran ┆ unt ┆ cri ┆ lua ┆ lua ┆ lua ┆ lua ┆ uir ┆ uir ┆ 3   ┆ ced ┆ ced ┆ enc ┆ enc ┆ Dat ┆ Dat ┆ Tim ┆ 4   ┆ --- ┆ ume ┆ 5   ┆ _1  ┆ ume ┆ 6   ┆ _2  ┆ ume ┆ ice ┆ ice ┆ lic ┆ ueD ┆ e_6 ┆ e_7 ┆ e_8 ┆ e_9 ┆ e_1 ┆ e_1 ┆ nti ┆ nti ┆ e_1 ┆ Tim ┆ cri ┆ eiv ┆ son ┆ rtD ┆ rtD ┆ Dat ┆ 7   ┆ tra ┆ tra ┆ cri ┆ e   ┆ erT ┆ erT ┆ her ┆ her ┆ ceR ┆ cri ┆ cri ┆ yNa ┆ 8   ┆ eVa ┆ tal ┆ bil ┆ bil ┆ 9   ┆ e   ┆ tra ┆ tra ┆ alD ┆ alD ┆ tra ┆ Exc ┆ Exc ┆ Exc ┆ Exc ┆ din ┆ din ┆ din ┆ imu ┆ cri ┆ ita ┆ ect ┆ imu ┆ rce ┆ uir ┆ cri ┆ ght ┆ e_1 ┆ ivi ┆ ivi ┆ erP ┆ 10  ┆ sch ┆ 11  ┆ sch ┆ Con ┆ sRe ┆ Awa ┆ ntr ┆ ntr ┆ ntr ┆ yNa ┆ tal ┆ nti ┆ nti ┆ nti ┆ din ┆ cur ┆ cur ┆ 12  ┆ mis ┆ mis ┆ rTh ┆ 13  ┆ ume ┆ ume ┆ _3  ┆ eNa ┆ cri ┆ e_1 ┆ cut ┆ cut ┆ cri ┆ rdi ┆ rdi ┆ rdi ┆ rdi ┆ poi ┆ tio ┆ eiv ┆ ume ┆ ume ┆ ume ┆ _4  ┆ eNa ┆ D   ┆ D_s ┆ rde ┆ rde ┆ e_1 ┆ ncy ┆ dDa ┆ dTi ┆ lua ┆ lua ┆ cri ┆ lua ┆ lua ┆ cri ┆ ntr ┆ ntr ┆ ntr ┆ nti ┆ nti ┆ e_1 ┆ tPr ┆ tPr ┆ tPr ┆ imu ┆ imu ┆ esh ┆ esh ┆ esh ┆ esh ┆ uir ┆ uir ┆ cri ┆ rdi ┆ rdi ┆ cri ┆ e_2 ┆ rdi ┆ rdi ┆ ght ┆ Dat ┆ Tim ┆ eet ┆ orm ┆ loy ┆ loy ┆ cri ┆ 14  ┆ sch ┆ ati ┆ EUN ┆ 15  ┆ sch ┆ eet ┆ yNa ┆ tal ┆ sCo ┆ cri ┆ 16  ┆ sch ┆ rat ┆ rat ┆ e_1 ┆ e_1 ┆ pan ┆ pan ┆ 17  ┆ 18  ┆ sch ┆ cur │
│ str ┆ ref ┆ y   ┆ y_t ┆ --- ┆ d   ┆ ctF ┆ ctF ┆ ctF ┆ ctF ┆ cti ┆ cti ┆ eUR ┆ str ┆ eme ┆ --- ┆ me  ┆ Zon ┆ --- ┆ fic ┆ fic ┆ --- ┆ --- ┆ one ┆ x   ┆ oni ┆ --- ┆ de  ┆ de_ ┆ eCo ┆ eCo ┆ ted ┆ ted ┆ mou ┆ mou ┆ lus ┆ lus ┆ ass ┆ ass ┆ ySu ┆ ySu ┆ ySu ┆ onM ┆ onM ┆ sDe ┆ --- ┆ eme ┆ --- ┆ mou ┆ mou ┆ lus ┆ lus ┆ ass ┆ ass ┆ Cod ┆ Cod ┆ pti ┆ ate ┆ ate ┆ --- ┆ eme ┆ --- ┆ eme ┆ lus ┆ lus ┆ eAm ┆ eAm ┆ tCo ┆ tee ┆ tee ┆ Rat ┆ pti ┆ tio ┆ tio ┆ tio ┆ tio ┆ eme ┆ eme ┆ --- ┆ ure ┆ ure ┆ yCo ┆ yCo ┆ e   ┆ e_1 ┆ e   ┆ --- ┆ str ┆ ntH ┆ --- ┆ --- ┆ ntH ┆ --- ┆ --- ┆ ntH ┆ Typ ┆ Typ ┆ ati ┆ ate ┆ --- ┆ --- ┆ --- ┆ --- ┆ 0   ┆ 1   ┆ fic ┆ fic ┆ 2   ┆ e_1 ┆ pti ┆ edT ┆ alS ┆ ate ┆ ate ┆ e_2 ┆ --- ┆ cti ┆ cti ┆ pti ┆ --- ┆ end ┆ end ┆ Ten ┆ Ten ┆ evi ┆ pti ┆ pti ┆ me_ ┆ --- ┆ lue ┆ Zon ┆ ity ┆ ity ┆ --- ┆ --- ┆ ctM ┆ ctM ┆ ura ┆ ura ┆ ctI ┆ lus ┆ lus ┆ lus ┆ lus ┆ gPr ┆ gPr ┆ gPr ┆ mQu ┆ pti ┆ tio ┆ edQ ┆ mQu ┆ _fi ┆ edC ┆ pti ┆ Num ┆ 3   ┆ tyC ┆ tyC ┆ rof ┆ --- ┆ eme ┆ --- ┆ eme ┆ tra ┆ cei ┆ rde ┆ ySu ┆ ySu ┆ ySu ┆ me_ ┆ Zon ┆ fic ┆ fic ┆ fic ┆ gPr ┆ eme ┆ eme ┆ --- ┆ sio ┆ sio ┆ res ┆ --- ┆ ntT ┆ ntT ┆ --- ┆ me  ┆ pti ┆ 4   ┆ ion ┆ ion ┆ pti ┆ ngC ┆ ngC ┆ ngC ┆ ngC ┆ ntI ┆ nCo ┆ edA ┆ ntT ┆ ntT ┆ ntT ┆ --- ┆ me_ ┆ --- ┆ che ┆ dOw ┆ dOw ┆ --- ┆ ID  ┆ te  ┆ me  ┆ tio ┆ tio ┆ pti ┆ tio ┆ tio ┆ pti ┆ ySu ┆ ySu ┆ ySu ┆ fic ┆ fic ┆ 5   ┆ ese ┆ ese ┆ ese ┆ mLo ┆ mTe ┆ old ┆ old ┆ old ┆ old ┆ eme ┆ eme ┆ pti ┆ ngC ┆ ngC ┆ pti ┆ --- ┆ ngC ┆ ngC ┆ Num ┆ e_3 ┆ e_2 ┆ Nam ┆ all ┆ eeQ ┆ eeQ ┆ pti ┆ --- ┆ eme ┆ ona ┆ ati ┆ --- ┆ eme ┆ Nam ┆ me_ ┆ Zon ┆ mbi ┆ pti ┆ --- ┆ eme ┆ ing ┆ ing ┆ --- ┆ 6   ┆ yTy ┆ yTy ┆ --- ┆ --- ┆ eme ┆ eme │
│     ┆ --- ┆ --- ┆ ype ┆ str ┆ --- ┆ old ┆ old ┆ old ┆ old ┆ ngP ┆ ngP ┆ I   ┆     ┆ Nam ┆ str ┆ --- ┆ e   ┆ str ┆ ati ┆ ati ┆ str ┆ str ┆ --- ┆ --- ┆ cMa ┆ str ┆ --- ┆ lis ┆ de  ┆ de_ ┆ Ove ┆ Ove ┆ nt  ┆ nt_ ┆ ive ┆ ive ┆ ifi ┆ ifi ┆ ben ┆ ben ┆ ben ┆ eas ┆ eas ┆ scr ┆ str ┆ Nam ┆ str ┆ nt_ ┆ nt_ ┆ ive ┆ ive ┆ ifi ┆ ifi ┆ e   ┆ e_l ┆ on  ┆ --- ┆ --- ┆ str ┆ Nam ┆ str ┆ ntP ┆ ive ┆ ive ┆ oun ┆ oun ┆ nst ┆ Typ ┆ Typ ┆ e   ┆ on_ ┆ nCr ┆ nCr ┆ nCr ┆ nCr ┆ ntT ┆ ntT ┆ str ┆ Cod ┆ Cod ┆ de  ┆ de_ ┆ --- ┆ --- ┆ --- ┆ str ┆     ┆ ash ┆ str ┆ str ┆ ash ┆ str ┆ str ┆ ash ┆ eCo ┆ eCo ┆ onM ┆ _1  ┆ str ┆ str ┆ str ┆ str ┆ --- ┆ --- ┆ ati ┆ ati ┆ --- ┆ --- ┆ on_ ┆ end ┆ itu ┆ --- ┆ _1  ┆ --- ┆ str ┆ ngS ┆ ngS ┆ on_ ┆ str ┆ erA ┆ erA ┆ der ┆ der ┆ sio ┆ on_ ┆ on_ ┆ 1   ┆ str ┆ --- ┆ e_1 ┆ Amo ┆ Amo ┆ str ┆ str ┆ odi ┆ odi ┆ tio ┆ tio ┆ D   ┆ ive ┆ ive ┆ ive ┆ ive ┆ ogr ┆ ogr ┆ ogr ┆ ant ┆ on_ ┆ nDe ┆ uan ┆ ant ┆ le  ┆ urr ┆ on_ ┆ eri ┆ --- ┆ ode ┆ ode ┆ ile ┆ str ┆ Nam ┆ str ┆ Nam ┆ ctI ┆ ved ┆ dIn ┆ ben ┆ ben ┆ ben ┆ 2   ┆ e_2 ┆ ati ┆ ati ┆ ati ┆ ogr ┆ ntN ┆ ntN ┆ str ┆ nMe ┆ nMe ┆ hol ┆ str ┆ ype ┆ ype ┆ str ┆ --- ┆ on_ ┆ --- ┆ Req ┆ Req ┆ on_ ┆ rit ┆ rit ┆ rit ┆ rit ┆ D   ┆ nst ┆ ppe ┆ ype ┆ ype ┆ ype ┆ str ┆ 1   ┆ str ┆ meN ┆ ner ┆ ner ┆ str ┆ --- ┆ --- ┆ --- ┆ nCr ┆ nCr ┆ on_ ┆ nCr ┆ nCr ┆ on_ ┆ ben ┆ ben ┆ ben ┆ ati ┆ ati ┆ --- ┆ nta ┆ nta ┆ nta ┆ tPr ┆ nde ┆ Qua ┆ Qua ┆ Qua ┆ Qua ┆ ntT ┆ ntT ┆ on_ ┆ rit ┆ rit ┆ on_ ┆ str ┆ rit ┆ rit ┆ eri ┆ --- ┆ --- ┆ e   ┆ yLo ┆ uan ┆ uan ┆ on_ ┆ str ┆ Nam ┆ lsR ┆ ona ┆ str ┆ Nam ┆ e_1 ┆ 3   ┆ e_3 ┆ nat ┆ on_ ┆ str ┆ Nam ┆ Yea ┆ Yea ┆ str ┆ --- ┆ peC ┆ peC ┆ str ┆ str ┆ Nam ┆ ntP │
│     ┆ str ┆ str ┆ --- ┆     ┆ str ┆ erI ┆ erS ┆ erS ┆ erS ┆ art ┆ art ┆ --- ┆     ┆ e   ┆     ┆ str ┆ --- ┆     ┆ onC ┆ onC ┆     ┆     ┆ str ┆ str ┆ il  ┆     ┆ str ┆ tUR ┆ --- ┆ lis ┆ ral ┆ ral ┆ --- ┆ cur ┆ Amo ┆ Amo ┆ cat ┆ cat ┆ tit ┆ tit ┆ tit ┆ ure ┆ ure ┆ ipt ┆     ┆ e_1 ┆     ┆ 1   ┆ cur ┆ Amo ┆ Amo ┆ cat ┆ cat ┆ --- ┆ ist ┆ --- ┆ str ┆ str ┆     ┆ e_2 ┆     ┆ roj ┆ Amo ┆ Amo ┆ t   ┆ t_c ┆ rai ┆ eCo ┆ eCo ┆ --- ┆ 1   ┆ ite ┆ ite ┆ ite ┆ ite ┆ ype ┆ ype ┆     ┆ e   ┆ e_l ┆ --- ┆ lis ┆ str ┆ str ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ _1  ┆     ┆     ┆ _2  ┆ de  ┆ de_ ┆ edi ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ onC ┆ onC ┆ str ┆ str ┆ 2   ┆ erQ ┆ ati ┆ str ┆ --- ┆ str ┆     ┆ yst ┆ yst ┆ 3   ┆     ┆ mou ┆ mou ┆ Amo ┆ Amo ┆ nFo ┆ 4   ┆ 5   ┆ --- ┆     ┆ str ┆ --- ┆ unt ┆ unt ┆     ┆     ┆ fic ┆ fic ┆ nMe ┆ nMe ┆ --- ┆ Amo ┆ Amo ┆ Amo ┆ Amo ┆ amC ┆ amC ┆ am  ┆ ity ┆ 6   ┆ scr ┆ tit ┆ ity ┆ --- ┆ icu ┆ 7   ┆ c   ┆ str ┆ --- ┆ _li ┆ URI ┆     ┆ e_3 ┆     ┆ e_4 ┆ ndi ┆ Ten ┆ dic ┆ tit ┆ tit ┆ tit ┆ --- ┆ --- ┆ onC ┆ onC ┆ onC ┆ amC ┆ ati ┆ ati ┆     ┆ tho ┆ tho ┆ dIn ┆     ┆ Cod ┆ Cod ┆     ┆ str ┆ 8   ┆ str ┆ uir ┆ uir ┆ 9   ┆ eri ┆ eri ┆ eri ┆ eri ┆ --- ┆ rai ┆ alQ ┆ Cod ┆ Cod ┆ Cod ┆     ┆ --- ┆     ┆ ame ┆ Nat ┆ Nat ┆     ┆ str ┆ str ┆ str ┆ ite ┆ ite ┆ 10  ┆ ite ┆ ite ┆ 11  ┆ tit ┆ tit ┆ tit ┆ onC ┆ onC ┆ str ┆ tio ┆ tio ┆ tio ┆ ese ┆ rer ┆ nti ┆ nti ┆ nti ┆ nti ┆ ype ┆ ype ┆ 12  ┆ eri ┆ eri ┆ 13  ┆     ┆ eri ┆ eri ┆ c_1 ┆ str ┆ str ┆ --- ┆ wTe ┆ tit ┆ tit ┆ 14  ┆     ┆ e_5 ┆ ece ┆ lsR ┆     ┆ e_6 ┆ --- ┆ --- ┆ --- ┆ ion ┆ 15  ┆     ┆ e_7 ┆ rsQ ┆ rsD ┆     ┆ str ┆ ode ┆ ode ┆     ┆     ┆ e_8 ┆ roj │
│     ┆     ┆     ┆ str ┆     ┆     ┆ D   ┆ tat ┆ tat ┆ tat ┆ yTy ┆ yTy ┆ str ┆     ┆ --- ┆     ┆     ┆ str ┆     ┆ ode ┆ ode ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ I   ┆ str ┆ tUR ┆ lCo ┆ lCo ┆ str ┆ ren ┆ unt ┆ unt ┆ ion ┆ ion ┆ y   ┆ yCo ┆ yCo ┆ --- ┆ _un ┆ ion ┆     ┆ --- ┆     ┆ --- ┆ ren ┆ unt ┆ unt ┆ ion ┆ ion ┆ str ┆ URI ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆ ect ┆ unt ┆ unt ┆ --- ┆ urr ┆ ntI ┆ de  ┆ de_ ┆ str ┆ --- ┆ ria ┆ ria ┆ ria ┆ ria ┆ Cod ┆ Cod ┆     ┆ --- ┆ ist ┆ str ┆ tUR ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ --- ┆ --- ┆ lis ┆ aNa ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ ode ┆ ode ┆     ┆     ┆ --- ┆ uan ┆ on  ┆     ┆ str ┆     ┆     ┆ emC ┆ emC ┆ --- ┆     ┆ nt  ┆ nt_ ┆ unt ┆ unt ┆ rmu ┆ --- ┆ --- ┆ str ┆     ┆     ┆ str ┆ --- ┆ _cu ┆     ┆     ┆ ati ┆ ati ┆ asu ┆ asu ┆ str ┆ unt ┆ unt ┆ unt ┆ unt ┆ ode ┆ ode ┆ --- ┆ --- ┆ --- ┆ ipt ┆ y   ┆ --- ┆ str ┆ laI ┆ --- ┆ --- ┆     ┆ str ┆ stU ┆ ID  ┆     ┆ --- ┆     ┆ --- ┆ cat ┆ der ┆ ato ┆ yCo ┆ yCo ┆ yCo ┆ str ┆ str ┆ ode ┆ ode ┆ ode ┆ ode ┆ ona ┆ ona ┆     ┆ dCo ┆ dCo ┆ dic ┆     ┆ e   ┆ e_l ┆     ┆     ┆ --- ┆     ┆ eme ┆ eme ┆ --- ┆ aTy ┆ aTy ┆ aSu ┆ aSu ┆ str ┆ ntI ┆ uan ┆ e_1 ┆ e_l ┆ e_n ┆     ┆ str ┆     ┆ --- ┆ ion ┆ ion ┆     ┆     ┆     ┆     ┆ ria ┆ ria ┆ --- ┆ ria ┆ ria ┆ --- ┆ y_1 ┆ yCo ┆ yCo ┆ ode ┆ ode ┆     ┆ nCo ┆ nCo ┆ nCo ┆ nta ┆ Awa ┆ ty  ┆ ty_ ┆ ty_ ┆ ty_ ┆ Cod ┆ Cod ┆ --- ┆ aTy ┆ aTy ┆ --- ┆     ┆ aSu ┆ aSu ┆ --- ┆     ┆     ┆ str ┆ nde ┆ y   ┆ yDe ┆ --- ┆     ┆ --- ┆ ive ┆ ece ┆     ┆ --- ┆ str ┆ str ┆ str ┆ Con ┆ --- ┆     ┆ --- ┆ uan ┆ esc ┆     ┆     ┆ --- ┆ _li ┆     ┆     ┆ --- ┆ ect │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ usC ┆ usC ┆ usC ┆ peC ┆ peC ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆ _li ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆ I   ┆ ntr ┆ ntr ┆     ┆ cyI ┆ --- ┆ _cu ┆ Cod ┆ Cod ┆ --- ┆ de  ┆ de_ ┆ str ┆ itC ┆ --- ┆     ┆ str ┆     ┆ str ┆ cyI ┆ _1  ┆ _cu ┆ Cod ┆ Cod ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆     ┆ Lot ┆ _2  ┆ _cu ┆ str ┆ enc ┆ ndi ┆ --- ┆ lis ┆     ┆ str ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ e   ┆ e_l ┆     ┆ str ┆ URI ┆     ┆ I   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ tUR ┆ me  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _1  ┆ _li ┆     ┆     ┆ str ┆ tit ┆ --- ┆     ┆     ┆     ┆     ┆ ode ┆ ode ┆ str ┆     ┆ --- ┆ cur ┆ --- ┆ _cu ┆ laD ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ rre ┆     ┆     ┆ onD ┆ onD ┆ re  ┆ re_ ┆     ┆ _3  ┆ _cu ┆ _4  ┆ _cu ┆ --- ┆ _li ┆ str ┆ str ┆ str ┆ ion ┆ --- ┆ str ┆     ┆ ndi ┆ str ┆ str ┆     ┆     ┆ RI  ┆ --- ┆     ┆ str ┆     ┆ str ┆ or  ┆ Qua ┆ r   ┆ de_ ┆ de_ ┆ de_ ┆     ┆     ┆ _2  ┆ _li ┆ _na ┆ _na ┆ lLe ┆ lLe ┆     ┆ de  ┆ de_ ┆ ato ┆     ┆ --- ┆ ist ┆     ┆     ┆ str ┆     ┆ ntC ┆ ntC ┆ str ┆ peC ┆ peC ┆ bTy ┆ bTy ┆     ┆ ndi ┆ tit ┆ --- ┆ ist ┆ ame ┆     ┆     ┆     ┆ str ┆ ali ┆ ali ┆     ┆     ┆     ┆     ┆ Typ ┆ Typ ┆ str ┆ Typ ┆ Typ ┆ str ┆ --- ┆ de_ ┆ de_ ┆ _3  ┆ _li ┆     ┆ de  ┆ de_ ┆ de_ ┆ tio ┆ rde ┆ --- ┆ 1   ┆ 2   ┆ 3   ┆ e_1 ┆ e_l ┆ str ┆ peC ┆ peC ┆ str ┆     ┆ bTy ┆ bTy ┆ str ┆     ┆     ┆     ┆ rsI ┆ --- ┆ scr ┆ str ┆     ┆ str ┆ dTe ┆ ive ┆     ┆ str ┆     ┆     ┆     ┆ tra ┆ str ┆     ┆ str ┆ tit ┆ rip ┆     ┆     ┆ str ┆ stU ┆     ┆     ┆ str ┆ Lot │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ ode ┆ ode ┆ ode ┆ ode ┆ ode ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ stU ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ act ┆ act ┆     ┆ D   ┆ str ┆ rre ┆ e   ┆ e_l ┆ str ┆ --- ┆ lis ┆     ┆ ode ┆ str ┆     ┆     ┆     ┆     ┆ D_1 ┆ --- ┆ rre ┆ e_1 ┆ e_l ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ ID  ┆ --- ┆ rre ┆     ┆ yID ┆ cat ┆ str ┆ tUR ┆     ┆     ┆ eCo ┆ eCo ┆ eCo ┆ eCo ┆ --- ┆ ist ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ I   ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ stU ┆     ┆     ┆     ┆ y   ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆ _li ┆     ┆     ┆ str ┆ ren ┆ str ┆ rre ┆ esc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ncy ┆     ┆     ┆ ura ┆ ura ┆ --- ┆ uni ┆     ┆ --- ┆ rre ┆ --- ┆ rre ┆ str ┆ stU ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆ cat ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆ nti ┆ --- ┆ 1   ┆ lis ┆ nam ┆     ┆     ┆ --- ┆ stU ┆ me  ┆ me  ┆ gis ┆ gis ┆     ┆ --- ┆ lis ┆ r   ┆     ┆ str ┆ URI ┆     ┆     ┆     ┆     ┆ ode ┆ ode ┆     ┆ ode ┆ ode ┆ peC ┆ peC ┆     ┆ cat ┆ y   ┆ str ┆ URI ┆ --- ┆     ┆     ┆     ┆     ┆ tyC ┆ tyC ┆     ┆     ┆     ┆     ┆ eCo ┆ eCo ┆     ┆ eCo ┆ eCo ┆     ┆ str ┆ 2   ┆ lis ┆ --- ┆ stU ┆     ┆ --- ┆ lis ┆ nam ┆ nQu ┆ dLo ┆ str ┆ --- ┆ --- ┆ --- ┆ --- ┆ ist ┆     ┆ ode ┆ ode ┆     ┆     ┆ peC ┆ peC ┆     ┆     ┆     ┆     ┆ ndi ┆ str ┆ ipt ┆     ┆     ┆     ┆ nde ┆ dTe ┆     ┆     ┆     ┆     ┆     ┆ cti ┆     ┆     ┆     ┆ y   ┆ tio ┆     ┆     ┆     ┆ RI  ┆     ┆     ┆     ┆ ID_ │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ _la ┆ _li ┆ --- ┆ _li ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RI  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ Amo ┆ Amo ┆     ┆ --- ┆     ┆ ncy ┆ --- ┆ ist ┆     ┆ str ┆ tUR ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ ncy ┆ --- ┆ ist ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ ncy ┆     ┆ --- ┆ or  ┆     ┆ I   ┆     ┆     ┆ de  ┆ de_ ┆ de_ ┆ de_ ┆ str ┆ URI ┆     ┆     ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ RI_ ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆ stU ┆     ┆     ┆     ┆ cyI ┆     ┆ ncy ┆ rip ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ID  ┆     ┆     ┆ tio ┆ tio ┆ str ┆ tCo ┆     ┆ str ┆ ncy ┆ str ┆ ncy ┆     ┆ RI  ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ or  ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆ ty  ┆ str ┆ --- ┆ tUR ┆ e   ┆     ┆     ┆ str ┆ RI_ ┆ --- ┆ --- ┆ lat ┆ lat ┆     ┆ str ┆ tUR ┆ --- ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ _li ┆     ┆ --- ┆ _li ┆ ode ┆ ode ┆     ┆ or  ┆ --- ┆     ┆ _1  ┆ str ┆     ┆     ┆     ┆     ┆ ode ┆ ode ┆     ┆     ┆     ┆     ┆ de_ ┆ de_ ┆     ┆ de_ ┆ de_ ┆     ┆     ┆ --- ┆ tUR ┆ str ┆ RI_ ┆     ┆ str ┆ tUR ┆ e   ┆ ant ┆ tsQ ┆     ┆ str ┆ str ┆ str ┆ str ┆ URI ┆     ┆ _1  ┆ _li ┆     ┆     ┆ ode ┆ ode ┆     ┆     ┆     ┆     ┆ cat ┆     ┆ ion ┆     ┆     ┆     ┆ rQu ┆ nde ┆     ┆     ┆     ┆     ┆     ┆ ngA ┆     ┆     ┆     ┆ --- ┆ n   ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ 1   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ ngu ┆ stU ┆ str ┆ stU ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ unt ┆ unt ┆     ┆ str ┆     ┆ ID  ┆ str ┆ URI ┆     ┆     ┆ I   ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ ID_ ┆ str ┆ URI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ ID_ ┆     ┆ str ┆ --- ┆     ┆ --- ┆     ┆     ┆ --- ┆ lis ┆ 1   ┆ lis ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ RI  ┆     ┆     ┆     ┆ D   ┆     ┆ ID  ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ nMe ┆ nMe ┆     ┆ de  ┆     ┆     ┆ ID_ ┆     ┆ ID_ ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ I_1 ┆ --- ┆     ┆     ┆     ┆ 2   ┆ str ┆ str ┆ ion ┆ ion ┆     ┆     ┆ I   ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ stU ┆     ┆ str ┆ stU ┆ --- ┆ _li ┆     ┆ --- ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ _li ┆     ┆     ┆     ┆     ┆ 2   ┆ lis ┆     ┆ 3   ┆ lis ┆     ┆     ┆ str ┆ I_2 ┆     ┆ 3   ┆     ┆     ┆ I   ┆ --- ┆ ity ┆ uan ┆     ┆     ┆     ┆     ┆     ┆ _1  ┆     ┆ --- ┆ stU ┆     ┆     ┆ _1  ┆ _li ┆     ┆     ┆     ┆     ┆ or  ┆     ┆ --- ┆     ┆     ┆     ┆ ant ┆ rQu ┆     ┆     ┆     ┆     ┆     ┆ uth ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ age ┆ RI  ┆     ┆ RI  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ _cu ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆ _1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ tUR ┆ --- ┆ tUR ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ asu ┆ asu ┆     ┆ --- ┆     ┆     ┆ 3   ┆     ┆ 4   ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ Cod ┆ Cod ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RI  ┆     ┆     ┆ RI  ┆ str ┆ stU ┆     ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆ stU ┆     ┆     ┆     ┆     ┆ --- ┆ tUR ┆     ┆ --- ┆ tUR ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆     ┆ --- ┆ str ┆ --- ┆ tit ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ RI_ ┆     ┆     ┆ --- ┆ stU ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆     ┆     ┆     ┆ ity ┆ ant ┆     ┆     ┆     ┆     ┆     ┆ ori ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str │

In [30]:
v.write_csv("../data/clean_data/licitaciones_construccion_vivienda.csv")

In [38]:
# Creamos y exportamos el dataset final con todos los campos que necesitemos.
df_f = df_by_year.unique(subset=["id"]).with_columns(
    pl.col("CityName").replace(
            {"València":"Valencia"},
            {"Santa Cruz de Tenerife":"Tenerife"})
        ).select([
        pl.col("id").alias("id"),
        pl.col("title"),
        pl.col("link_href"),
        pl.col("ResultCode").alias("status"),
        pl.col("year"),
        pl.col("EstimatedOverallContractAmount").alias("estimatedAmount"),
        pl.col("PayableAmount").alias("payableAmount"),
        pl.col("ContractingPartyTypeCode").alias("organo"),
        pl.col("PostalZone").alias("PostalCode"),
        pl.col("CityName").alias("city"),
        pl.col("DurationMeasure").alias("duration"),
        pl.col("ID_2").alias("cif_provider"),
        pl.col("Name_5").alias("name_provider"),
        pl.col("n_viviendas")
    ]).sort(by="status", descending=True)

df_f.write_json("../my-app/src/lib/components/datos/test.json")
df_f.write_csv("../my-app/src/lib/components/datos/test.csv")

In [ ]:
len(df_f)

In [ ]:
count = df_f["cif_provider"].len()
count

In [ ]:
unique_count = df_f["cif_provider"].n_unique()
unique_count

In [ ]:
payableAmount_by_year = df_f.group_by("year").agg([
    pl.col("payableAmount").str.to_decimal(scale=1).sum()
])
payableAmount_by_year